; 10 probs, max 3 goals, 5 objs

(setq  *TEST-PROBS*
    '((BB3-1 (and (on C B) (on B A))
            ((object D)
             (on-table D)
             (object B)
             (on B D)
             (clear B)
             (object C)
             (clear C)
             (on-table C)
             (object A)
             (holding A)))
     (BB3-2 (and (holding E) (on A D) (on C B))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (object E)
             (on-table E)
             (object D)
             (on D E)
             (clear D)
             (object A)
             (holding A)))
     (BB3-3 (arm-empty)
            ((object B)
             (clear B)
             (on-table B)
             (object C)
             (clear C)
             (on-table C)
             (object A)
             (holding A)))
     (BB3-4 (and (holding B) (clear C) (on C A))
            ((object A)
             (clear A)
             (on-table A)
             (object B)
             (clear B)
             (on-table B)
             (object C)
             (clear C)
             (on-table C)
             (arm-empty)))
     (BB3-5 (and (on A C) (holding D) (on B A))
            ((object A)
             (clear A)
             (on-table A)
             (object B)
             (clear B)
             (on-table B)
             (object C)
             (clear C)
             (on-table C)
             (object D)
             (clear D)
             (on-table D)
             (arm-empty)))
     (BB3-6 (and (on A D) (on C A))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (object D)
             (clear D)
             (on-table D)
             (object A)
             (holding A)))
     (BB3-7 (holding D)
            ((object D)
             (on-table D)
             (object C)
             (on C D)
             (object A)
             (on A C)
             (clear A)
             (object B)
             (clear B)
             (on-table B)
             (arm-empty)))
     (BB3-8 (and (clear C) (arm-empty))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (object D)
             (clear D)
             (on-table D)
             (object A)
             (holding A)))
     (BB3-9 (and (on-table A) (clear C) (on C A) (clear B))
            ((object B)
             (on-table B)
             (object A)
             (on A B)
             (clear A)
             (object C)
             (clear C)
             (on-table C)
             (arm-empty)))
     (BB3-10 (and (on-table A) (clear C) (arm-empty))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (object A)
             (holding A)))))
