; 10 probs 3-4 goals, 3-4 objs

(setq *TEST-PROBS*
    '((BB4-1 (and (holding C) (on-table A) (on B A))
           ((object B)
            (clear B)
            (on-table B)
            (object C)
            (clear C)
            (on-table C)
            (object A)
            (holding A)))
     (BB4-2 (and (holding C) (on-table A))
           ((object B)
            (on-table B)
            (object A)
            (on A B)
            (clear A)
            (object C)
            (clear C)
            (on-table C)
	    (object D)
	    (on-table D)
	    (clear D)
            (arm-empty)))
     (BB4-3 (and (clear B) (on-table C) (holding A))
            ((object B)
             (on-table B)
             (object A)
             (on A B)
             (clear A)
             (object C)
             (clear C)
             (on-table C)
             (arm-empty)))
     (BB4-4 (and (on B A) (clear B) (on A C))
            ((object B)
             (on-table B)
             (object A)
             (on A B)
             (clear A)
             (object C)
             (clear C)
             (on-table C)
             (arm-empty)))
     (BB4-5 (and (arm-empty) (on A C) (on-table B))
            ((object A)
             (clear A)
             (on-table A)
             (object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (arm-empty)))
     (BB4-6 (and (clear C) (on-table C))
            ((object A)
             (clear A)
             (on-table A)
             (object B)
             (clear B)
             (on-table B)
             (object C)
             (clear C)
             (on-table C)
             (arm-empty)))
     (BB4-7 (and (clear A) (on A C))
            ((object B)
             (clear B)
             (on-table B)
             (object C)
             (clear C)
             (on-table C)
             (object A)
             (holding A)))
     (BB4-8 (and (on A C) (on-table B))
            ((object A)
             (clear A)
             (on-table A)
             (object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (arm-empty)))
     (BB4-9 (and  (on-table C) (on-table B) (on A B))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (object A)
             (holding A)))
     (BB4-10 (and (on A B) (on B C))
            ((object C)
             (on-table C)
             (object A)
             (on A C)
             (clear A)
             (object B)
             (clear B)
             (on-table B)
             (arm-empty)))))

(setq *AUX-COMMANDS*
  '((BB4-9 (optimal-path (cadr *ALL-NODES*)))))
