; 10 probs max 4 goals, 4 objs.
(setq *TEST-PROBS*
    '((BB5-1 (and (on-table A) (on C B) (on B A))
            ((object B)
             (on-table B)
             (object A)
             (on A B)
             (clear A)
             (object C)
             (clear C)
             (on-table C)
             (arm-empty)))
     (BB5-2 (and (on-table A) (on-table C) (clear B))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (object A)
             (on A B)
             (clear A)
             (arm-empty)))
     (BB5-3 (and (on-table B) (on-table C) (clear B) (on A C))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (object A)
             (on A B)
             (clear A)
             (arm-empty)))
     (BB5-4 (and (on C B) (on-table B) (on-table D))
            ((object D)
             (on-table D)
             (object B)
             (on B D)
             (clear B)
             (object C)
             (clear C)
             (on-table C)
             (object A)
             (holding A)))
     (BB5-5 (and (on A D) (clear B))
            ((object D)
             (on-table D)
             (object C)
             (on C D)
             (object B)
             (on B C)
             (object A)
             (on A B)
             (clear A)
             (arm-empty)))
     (BB5-6 (and (on-table B) (clear B) (clear C))
            ((object A)
             (clear A)
             (on-table A)
             (object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (arm-empty)))
     (BB5-7 (and (on B A) (clear B) (on-table A) (holding C))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (object A)
             (holding A)))
     (BB5-8 (and (on C A) (on-table A) (clear D))
            ((object D)
             (on-table D)
             (object C)
             (on C D)
             (object B)
             (on B C)
             (clear B)
             (object A)
             (holding A)))
     (BB5-9 (and (arm-empty) (on A C) (on C B))
            ((object B)
             (clear B)
             (on-table B)
             (object C)
             (clear C)
             (on-table C)
             (object D)
             (clear D)
             (on-table D)
             (object A)
             (holding A)))
     (BB5-10 (and (holding A) (on D B))
            ((object B)
             (on-table B)
             (object A)
             (on A B)
             (clear A)
             (object D)
             (on-table D)
             (object C)
             (on C D)
             (clear C)
             (arm-empty)))))
