; 10 probs, max 5 objs, 4 goals

(setq *TEST-PROBS*
    '((BB6-1 (and (on E B) (on-table B) (on A C))
           ((object A)
            (clear A)
            (on-table A)
            (object D)
            (on-table D)
            (object C)
            (on C D)
            (object B)
            (on B C)
            (clear B)
            (object E)
            (clear E)
            (on-table E)
            (arm-empty)))
     (BB6-2 (and (on C A) (clear B))
           ((object B)
            (on-table B)
            (object A)
            (on A B)
            (clear A)
            (object E)
            (on-table E)
            (object C)
            (on C E)
            (clear C)
            (object D)
            (holding D)))
     (BB6-3 (and (on-table B) (clear C) (holding A))
           ((object A)
            (clear A)
            (on-table A)
            (object C)
            (on-table C)
            (object B)
            (on B C)
            (clear B)
            (arm-empty)))
     (BB6-4 (and (on D E) (on C D) (on-table A) (holding B))
            ((object D)
             (on-table D)
             (object C)
             (on C D)
             (object B)
             (on B C)
             (clear B)
             (object E)
             (clear E)
             (on-table E)
             (object A)
             (holding A)))
     (BB6-5 (and (clear C) (on-table B) (holding A))
            ((object A)
             (clear A)
             (on-table A)
             (object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (arm-empty)))
     (BB6-6 (and (on A E) (clear C) (on D A) (on-table B))
            ((object D)
             (on-table D)
             (object A)
             (on A D)
             (clear A)
             (object B)
             (clear B)
             (on-table B)
             (object C)
             (clear C)
             (on-table C)
             (object E)
             (clear E)
             (on-table E)
             (arm-empty)))
     (BB6-7 (and (on D A) (on E D) (clear C) (on-table C))
            ((object A)
             (clear A)
             (on-table A)
             (object B)
             (clear B)
             (on-table B)
             (object D)
             (on-table D)
             (object C)
             (on C D)
             (clear C)
             (object E)
             (clear E)
             (on-table E)
             (arm-empty)))
     (BB6-8 (and (clear B) (on D C) (on-table C))
            ((object D)
             (on-table D)
             (object C)
             (on C D)
             (object A)
             (on A C)
             (clear A)
             (object B)
             (clear B)
             (on-table B)
             (arm-empty)))
     (BB6-9 (and (on C E) (clear D))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (object A)
             (on A B)
             (clear A)
             (object D)
             (clear D)
             (on-table D)
             (object E)
             (clear E)
             (on-table E)
             (arm-empty)))
     (BB6-10 (and (on C B) (on B D) (clear A))
            ((object D)
             (on-table D)
             (object C)
             (on C D)
             (object B)
             (on B C)
             (object A)
             (on A B)
             (clear A)
             (arm-empty)))))

(setq *AUX-COMMANDS*
 '((BB6-2 (optimal-path (cadr *ALL-NODES*)))))
