;  9 probs
(setq *TEST-PROBS*
    '((BB7-1 (and (on-table B) (on-table C) (clear B) (on A C))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (object A)
             (on A B)
             (clear A)
             (arm-empty)))
     (BB7-2 (and (on C A) (on D B) (on A E) (clear D))
            ((object D)
             (on-table D)
             (object C)
             (on C D)
             (object B)
             (on B C)
             (object A)
             (on A B)
             (clear A)
             (object E)
             (clear E)
             (on-table E)
             (arm-empty)))
     (BB7-3 (and (on B A) (on A C) (clear B))
            ((object A)
             (clear A)
             (on-table A)
             (object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (arm-empty)))
     (BB7-4 (and (on D C) (clear D) (on A B) (holding E))
            ((object E)
             (on-table E)
             (object D)
             (on D E)
             (object C)
             (on C D)
             (object B)
             (on B C)
             (clear B)
             (object A)
             (holding A)))
     (BB7-5 (and (clear A) (holding B))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (object A)
             (holding A)))
; bug showed up
;     (BB7-6 (and (on-table D) (on A E) (on B D) (clear A))
;            ((object E)
;             (on-table E)
;             (object D)
;             (on D E)
;             (object C)
;             (on C D)
;             (object B)
;             (on B C)
;             (clear B)
;             (object A)
;             (holding A)))
     (BB7-7 (and (clear B) (holding A))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (object A)
             (on A B)
             (clear A)
             (object D)
             (clear D)
             (on-table D)
             (arm-empty)))
     (BB7-8 (and (arm-empty) (on-table C) (on A E))
            ((object E)
             (on-table E)
             (object D)
             (on D E)
             (object C)
             (on C D)
             (object B)
             (on B C)
             (clear B)
             (object A)
             (holding A)))
     (BB7-9 (and (clear A) (arm-empty) (on C E) (on B D) (on-table D))
            ((object E)
             (on-table E)
             (object D)
             (on D E)
             (object C)
             (on C D)
             (object B)
             (on B C)
             (clear B)
             (object A)
             (holding A)))
     (BB7-10 (and (on-table E) (on D B) (on-table B))
            ((object C)
             (on-table C)
             (object B)
             (on B C)
             (clear B)
             (object E)
             (on-table E)
             (object D)
             (on D E)
             (clear D)
             (object A)
             (holding A)))))
