(load-goal '(arm-empty))

(load-start-state '((object A)
             (object B)
             (holding A)
             (on-table B)
             (clear B)
             (object C)
             (on-table C)
             (clear C)))
