; 13 problems: 3 goals, 2 rooms (SW1)
(setq *TEST-PROBS*
    '((SS4-2 (and (inroom robot rm1) (dr-closed dr12) (inroom A rm1))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-closed dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable C)
             (carriable A)
             (is-object key12)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom C rm2)
             (inroom B rm2)
             (inroom A rm2)
             (inroom key12 rm2)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-3 (and (dr-closed dr12) (inroom A rm1) (inroom key12 rm1))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable A)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm1)
             (inroom A rm2)
             (inroom key12 rm1)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-4 (and (inroom B rm1) (locked dr12) (inroom key12 rm1))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable B)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm2)
             (inroom A rm1)
             (inroom key12 rm2)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-5 (and (arm-empty) (dr-closed dr12) (inroom A rm1))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (next-to A B)
             (next-to B A)
             (dr-closed dr12)
             (locked dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable A)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm2)
             (inroom A rm2)
             (inroom key12 rm2)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-6 (and (arm-empty) (dr-closed dr12) (inroom B rm2))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable B)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm1)
             (inroom A rm2)
             (inroom key12 rm2)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-7 (and (locked dr12) (inroom key12 rm2))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable B)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm2)
             (inroom A rm2)
             (inroom key12 rm1)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-8 (and (unlocked dr12) (dr-closed dr12) (inroom A rm1))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (next-to C A)
             (next-to A C)
             (unlocked dr12)
             (dr-closed dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (carriable C)
             (carriable A)
             (is-object key12)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom C rm2)
             (inroom B rm1)
             (inroom A rm2)
             (inroom key12 rm2)
             (inroom robot rm1)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-9 (and (unlocked dr12) (inroom key12 rm1) (dr-open dr12))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (dr-closed dr12)
             (locked dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable B)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm2)
             (inroom A rm1)
             (inroom key12 rm2)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-10 (and (next-to A B) (inroom B rm1))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (carriable B)
             (pushable A)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm1)
             (inroom A rm2)
             (inroom key12 rm1)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-11 (and (dr-closed dr12) (inroom key12 rm2) (inroom A rm2))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (carriable A)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm1)
             (inroom A rm1)
             (inroom key12 rm2)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-12 (and (inroom B rm2) (inroom robot rm1))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (carriable B)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm1)
             (inroom A rm1)
             (inroom key12 rm1)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-13 (and (inroom key12 rm2) (inroom robot rm1) (dr-closed dr12))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable B)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm1)
             (inroom A rm2)
             (inroom key12 rm1)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS4-14 (and (inroom key12 rm2) (dr-closed dr12) (next-to B C))
            ((arm-empty)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm2)
             (is-room rm1)
             (is-door dr12)
             (pushable B)
             (is-object key12)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom C rm2)
             (inroom B rm1)
             (inroom A rm2)
             (inroom key12 rm2)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))))




(setq *AUX-COMMANDS*
 '((SS4-4 (optimal-path (cadr *ALL-NODES*)))
   (SS4-14 (optimal-path (cadr *ALL-NODES*)))))
