;  10 probs, SW2 -- 4 rms, 4 obs, 3 goals.

(setq *TEST-PROBS*
    '((SS6-1 (and (locked dr12) (unlocked dr34) (inroom A rm4))
            ((arm-empty)
             (dr-to-rm dr34 rm4)
             (dr-to-rm dr34 rm3)
             (connects dr34 rm4 rm3)
             (connects dr34 rm3 rm4)
             (dr-to-rm dr23 rm3)
             (dr-to-rm dr23 rm2)
             (connects dr23 rm3 rm2)
             (connects dr23 rm2 rm3)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr34)
             (dr-closed dr34)
             (unlocked dr23)
             (dr-open dr23)
             (unlocked dr12)
             (dr-closed dr12)
             (is-room rm4)
             (is-room rm3)
             (is-room rm2)
             (is-room rm1)
             (is-door dr34)
             (is-door dr23)
             (is-door dr12)
             (pushable A)
             (is-object key12)
             (is-object B)
             (is-object A)
             (inroom B rm2)
             (inroom A rm1)
             (inroom key12 rm4)
             (inroom robot rm3)
             (carriable key12)
             (is-key dr12 key12)))
     (SS6-2 (and (locked dr12) (inroom C rm1) (inroom A rm3))
            ((arm-empty)
             (dr-to-rm dr34 rm4)
             (dr-to-rm dr34 rm3)
             (connects dr34 rm4 rm3)
             (connects dr34 rm3 rm4)
             (dr-to-rm dr23 rm3)
             (dr-to-rm dr23 rm2)
             (connects dr23 rm3 rm2)
             (connects dr23 rm2 rm3)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr34)
             (dr-closed dr34)
             (unlocked dr23)
             (dr-open dr23)
             (unlocked dr12)
             (dr-closed dr12)
             (is-room rm4)
             (is-room rm3)
             (is-room rm2)
             (is-room rm1)
             (is-door dr34)
             (is-door dr23)
             (is-door dr12)
             (carriable C)
             (carriable A)
             (is-object key12)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom C rm1)
             (inroom B rm4)
             (inroom A rm3)
             (inroom key12 rm2)
             (inroom robot rm1)
             (carriable key12)
             (is-key dr12 key12)))
     (SS6-3 (and (unlocked dr23) (locked dr12) (dr-open dr23))
            ((arm-empty)
             (dr-to-rm dr34 rm4)
             (dr-to-rm dr34 rm3)
             (connects dr34 rm4 rm3)
             (connects dr34 rm3 rm4)
             (dr-to-rm dr23 rm3)
             (dr-to-rm dr23 rm2)
             (connects dr23 rm3 rm2)
             (connects dr23 rm2 rm3)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr34)
             (dr-open dr34)
             (unlocked dr23)
             (dr-closed dr23)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm4)
             (is-room rm3)
             (is-room rm2)
             (is-room rm1)
             (is-door dr34)
             (is-door dr23)
             (is-door dr12)
             (carriable B)
             (is-object key12)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom C rm2)
             (inroom B rm1)
             (inroom A rm4)
             (inroom key12 rm3)
             (inroom robot rm2)
             (carriable key12)
             (is-key dr12 key12)))
     (SS6-4 (and (unlocked dr23) (locked dr12) (dr-closed dr12))
            ((arm-empty)
             (dr-to-rm dr34 rm4)
             (dr-to-rm dr34 rm3)
             (connects dr34 rm4 rm3)
             (connects dr34 rm3 rm4)
             (dr-to-rm dr23 rm3)
             (dr-to-rm dr23 rm2)
             (connects dr23 rm3 rm2)
             (connects dr23 rm2 rm3)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr34)
             (dr-closed dr34)
             (unlocked dr23)
             (dr-open dr23)
             (unlocked dr12)
             (dr-closed dr12)
             (is-room rm4)
             (is-room rm3)
             (is-room rm2)
             (is-room rm1)
             (is-door dr34)
             (is-door dr23)
             (is-door dr12)
             (carriable C)
             (pushable B)
             (carriable A)
             (is-object key12)
             (is-object D)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom D rm4)
             (inroom C rm3)
             (inroom B rm2)
             (inroom A rm1)
             (inroom key12 rm4)
             (inroom robot rm3)
             (carriable key12)
             (is-key dr12 key12)))
     (SS6-5 (and (dr-closed dr34) (dr-closed dr12) (inroom C rm3))
            ((arm-empty)
             (dr-to-rm dr34 rm4)
             (dr-to-rm dr34 rm3)
             (connects dr34 rm4 rm3)
             (connects dr34 rm3 rm4)
             (dr-to-rm dr23 rm3)
             (dr-to-rm dr23 rm2)
             (connects dr23 rm3 rm2)
             (connects dr23 rm2 rm3)
             (dr-to-rm dr12 rm2)
             (dr-to-rm dr12 rm1)
             (connects dr12 rm2 rm1)
             (connects dr12 rm1 rm2)
             (unlocked dr34)
             (dr-open dr34)
             (unlocked dr23)
             (dr-closed dr23)
             (unlocked dr12)
             (dr-open dr12)
             (is-room rm4)
             (is-room rm3)
             (is-room rm2)
             (is-room rm1)
             (is-door dr34)
             (is-door dr23)
             (is-door dr12)
             (carriable C)
             (pushable A)
             (is-object key12)
             (is-object D)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom D rm1)
             (inroom C rm4)
             (inroom B rm3)
             (inroom A rm2)
             (inroom key12 rm1)
             (inroom robot rm4)
             (carriable key12)
             (is-key dr12 key12)))
     (SS6-6 (and (unlocked dr23) (dr-open dr23) (inroom B rm2))
           ((arm-empty)
            (dr-to-rm dr34 rm4)
            (dr-to-rm dr34 rm3)
            (connects dr34 rm4 rm3)
            (connects dr34 rm3 rm4)
            (dr-to-rm dr23 rm3)
            (dr-to-rm dr23 rm2)
            (connects dr23 rm3 rm2)
            (connects dr23 rm2 rm3)
            (dr-to-rm dr12 rm2)
            (dr-to-rm dr12 rm1)
            (connects dr12 rm2 rm1)
            (connects dr12 rm1 rm2)
            (unlocked dr34)
            (dr-open dr34)
            (unlocked dr23)
            (dr-closed dr23)
            (unlocked dr12)
            (dr-open dr12)
            (is-room rm4)
            (is-room rm3)
            (is-room rm2)
            (is-room rm1)
            (is-door dr34)
            (is-door dr23)
            (is-door dr12)
            (pushable B)
            (is-object key12)
            (is-object B)
            (is-object A)
            (inroom B rm3)
            (inroom A rm2)
            (inroom key12 rm1)
            (inroom robot rm4)
            (carriable key12)
            (is-key dr12 key12)))
     (SS6-7 (inroom robot rm3) 
           ((arm-empty)
            (dr-to-rm dr34 rm4)
            (dr-to-rm dr34 rm3)
            (connects dr34 rm4 rm3)
            (connects dr34 rm3 rm4)
            (dr-to-rm dr23 rm3)
            (dr-to-rm dr23 rm2)
            (connects dr23 rm3 rm2)
            (connects dr23 rm2 rm3)
            (dr-to-rm dr12 rm2)
            (dr-to-rm dr12 rm1)
            (connects dr12 rm2 rm1)
            (connects dr12 rm1 rm2)
            (unlocked dr34)
            (dr-closed dr34)
            (unlocked dr23)
            (dr-open dr23)
            (unlocked dr12)
            (dr-closed dr12)
            (is-room rm4)
            (is-room rm3)
            (is-room rm2)
            (is-room rm1)
            (is-door dr34)
            (is-door dr23)
            (is-door dr12)
            (pushable B)
            (pushable A)
            (is-object key12)
            (is-object C)
            (is-object B)
            (is-object A)
            (inroom C rm1)
            (inroom B rm4)
            (inroom A rm3)
            (inroom key12 rm2)
            (inroom robot rm1)
            (carriable key12)
            (is-key dr12 key12)))
     (SS6-8 (and (dr-closed dr23) (inroom robot rm2) (arm-empty))
           ((arm-empty)
            (dr-to-rm dr34 rm4)
            (dr-to-rm dr34 rm3)
            (connects dr34 rm4 rm3)
            (connects dr34 rm3 rm4)
            (dr-to-rm dr23 rm3)
            (dr-to-rm dr23 rm2)
            (connects dr23 rm3 rm2)
            (connects dr23 rm2 rm3)
            (dr-to-rm dr12 rm2)
            (dr-to-rm dr12 rm1)
            (connects dr12 rm2 rm1)
            (connects dr12 rm1 rm2)
            (unlocked dr34)
            (dr-open dr34)
            (unlocked dr23)
            (dr-closed dr23)
            (unlocked dr12)
            (dr-open dr12)
            (is-room rm4)
            (is-room rm3)
            (is-room rm2)
            (is-room rm1)
            (is-door dr34)
            (is-door dr23)
            (is-door dr12)
            (pushable B)
            (is-object key12)
            (is-object C)
            (is-object B)
            (is-object A)
            (inroom C rm3)
            (inroom B rm2)
            (inroom A rm1)
            (inroom key12 rm4)
            (inroom robot rm3)
            (carriable key12)
            (is-key dr12 key12)))
     (SS6-9 (and (unlocked dr23) (inroom A rm2) (dr-closed dr34))
           ((arm-empty)
            (dr-to-rm dr34 rm4)
            (dr-to-rm dr34 rm3)
            (connects dr34 rm4 rm3)
            (connects dr34 rm3 rm4)
            (dr-to-rm dr23 rm3)
            (dr-to-rm dr23 rm2)
            (connects dr23 rm3 rm2)
            (connects dr23 rm2 rm3)
            (dr-to-rm dr12 rm2)
            (dr-to-rm dr12 rm1)
            (connects dr12 rm2 rm1)
            (connects dr12 rm1 rm2)
            (unlocked dr34)
            (dr-closed dr34)
            (unlocked dr23)
            (dr-open dr23)
            (dr-closed dr12)
            (locked dr12)
            (is-room rm4)
            (is-room rm3)
            (is-room rm2)
            (is-room rm1)
            (is-door dr34)
            (is-door dr23)
            (is-door dr12)
            (carriable D)
            (pushable B)
            (pushable A)
            (is-object key12)
            (is-object D)
            (is-object C)
            (is-object B)
            (is-object A)
            (inroom D rm4)
            (inroom C rm3)
            (inroom B rm2)
            (inroom A rm1)
            (inroom key12 rm4)
            (inroom robot rm3)
            (carriable key12)
            (is-key dr12 key12)))
     (SS6-10 (and (dr-open dr34) (inroom A rm4) (inroom B rm1))
           ((arm-empty)
            (dr-to-rm dr34 rm4)
            (dr-to-rm dr34 rm3)
            (connects dr34 rm4 rm3)
            (connects dr34 rm3 rm4)
            (dr-to-rm dr23 rm3)
            (dr-to-rm dr23 rm2)
            (connects dr23 rm3 rm2)
            (connects dr23 rm2 rm3)
            (dr-to-rm dr12 rm2)
            (dr-to-rm dr12 rm1)
            (connects dr12 rm2 rm1)
            (connects dr12 rm1 rm2)
            (unlocked dr34)
            (dr-open dr34)
            (unlocked dr23)
            (dr-closed dr23)
            (unlocked dr12)
            (dr-open dr12)
            (is-room rm4)
            (is-room rm3)
            (is-room rm2)
            (is-room rm1)
            (is-door dr34)
            (is-door dr23)
            (is-door dr12)
            (pushable B)
            (pushable A)
            (is-object key12)
            (is-object B)
            (is-object A)
            (inroom B rm3)
            (inroom A rm2)
            (inroom key12 rm1)
            (inroom robot rm4)
            (carriable key12)
            (is-key dr12 key12)))))




(setq AUX-COMMANDS
 '((SS6-1 (optimal-path (cadr *ALL-NODES*)))))

