; 7 strips probs SW3, 6 rms, 3 objs, 3 goals.

(setq *TEST-PROBS*
    '((SS7-1 (and (inroom robot bath)
                 (dr-closed dr-kitch-droom))
            ((arm-empty)
             (dr-to-rm dr-kitch-droom droom)
             (dr-to-rm dr-kitch-droom kitch)
             (connects dr-kitch-droom droom kitch)
             (connects dr-kitch-droom kitch droom)
             (dr-to-rm dr-hall-kitch kitch)
             (dr-to-rm dr-hall-kitch hall)
             (connects dr-hall-kitch kitch hall)
             (connects dr-hall-kitch hall kitch)
             (dr-to-rm dr-lroom-droom droom)
             (dr-to-rm dr-lroom-droom lroom)
             (connects dr-lroom-droom droom lroom)
             (connects dr-lroom-droom lroom droom)
             (dr-to-rm dr-den-droom lroom)
             (dr-to-rm dr-den-droom den)
             (connects dr-den-droom lroom den)
             (connects dr-den-droom den lroom)
             (dr-to-rm dr-den-kitch kitch)
             (dr-to-rm dr-den-kitch den)
             (connects dr-den-kitch kitch den)
             (connects dr-den-kitch den kitch)
             (dr-to-rm dr-den-bath bath)
             (dr-to-rm dr-den-bath den)
             (connects dr-den-bath bath den)
             (connects dr-den-bath den bath)
             (unlocked dr-kitch-droom)
             (dr-open dr-kitch-droom)
             (unlocked dr-hall-kitch)
             (dr-closed dr-hall-kitch)
             (unlocked dr-lroom-droom)
             (dr-open dr-lroom-droom)
             (unlocked dr-den-droom)
             (dr-closed dr-den-droom)
             (unlocked dr-den-kitch)
             (dr-open dr-den-kitch)
             (unlocked dr-den-bath)
             (dr-closed dr-den-bath)
             (is-room hall)
             (is-room kitch)
             (is-room droom)
             (is-room lroom)
             (is-room bath)
             (is-room den)
             (is-door dr-kitch-droom)
             (is-door dr-hall-kitch)
             (is-door dr-lroom-droom)
             (is-door dr-den-droom)
             (is-door dr-den-kitch)
             (is-door dr-den-bath)
             (carriable B)
             (is-object den-key)
             (is-object bath-key)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom C droom)
             (inroom B den)
             (inroom A hall)
             (inroom den-key lroom)
             (inroom bath-key droom)
             (inroom robot lroom)
             (carriable den-key)
             (is-key dr-den-kitch den-key)
             (carriable bath-key)
             (is-key dr-den-bath bath-key)))
     (SS7-2 (and (inroom bath-key hall)
                 (dr-closed dr-kitch-droom))
            ((arm-empty)
             (dr-to-rm dr-kitch-droom droom)
             (dr-to-rm dr-kitch-droom kitch)
             (connects dr-kitch-droom droom kitch)
             (connects dr-kitch-droom kitch droom)
             (dr-to-rm dr-hall-kitch kitch)
             (dr-to-rm dr-hall-kitch hall)
             (connects dr-hall-kitch kitch hall)
             (connects dr-hall-kitch hall kitch)
             (dr-to-rm dr-lroom-droom droom)
             (dr-to-rm dr-lroom-droom lroom)
             (connects dr-lroom-droom droom lroom)
             (connects dr-lroom-droom lroom droom)
             (dr-to-rm dr-den-droom lroom)
             (dr-to-rm dr-den-droom den)
             (connects dr-den-droom lroom den)
             (connects dr-den-droom den lroom)
             (dr-to-rm dr-den-kitch kitch)
             (dr-to-rm dr-den-kitch den)
             (connects dr-den-kitch kitch den)
             (connects dr-den-kitch den kitch)
             (dr-to-rm dr-den-bath bath)
             (dr-to-rm dr-den-bath den)
             (connects dr-den-bath bath den)
             (connects dr-den-bath den bath)
             (unlocked dr-kitch-droom)
             (dr-open dr-kitch-droom)
             (unlocked dr-hall-kitch)
             (dr-closed dr-hall-kitch)
             (unlocked dr-lroom-droom)
             (dr-open dr-lroom-droom)
             (unlocked dr-den-droom)
             (dr-closed dr-den-droom)
             (unlocked dr-den-kitch)
             (dr-open dr-den-kitch)
             (dr-closed dr-den-bath)
             (locked dr-den-bath)
             (is-room hall)
             (is-room kitch)
             (is-room droom)
             (is-room lroom)
             (is-room bath)
             (is-room den)
             (is-door dr-kitch-droom)
             (is-door dr-hall-kitch)
             (is-door dr-lroom-droom)
             (is-door dr-den-droom)
             (is-door dr-den-kitch)
             (is-door dr-den-bath)
             (carriable C)
             (pushable B)
             (pushable A)
             (is-object den-key)
             (is-object bath-key)
             (is-object C)
             (is-object B)
             (is-object A)
             (inroom C bath)
             (inroom B den)
             (inroom A hall)
             (inroom den-key den)
             (inroom bath-key droom)
             (inroom robot den)
             (carriable den-key)
             (is-key dr-den-kitch den-key)
             (carriable bath-key)
             (is-key dr-den-bath bath-key)))
     (SS7-3 (inroom B bath)
           ((arm-empty)
            (dr-to-rm dr-kitch-droom droom)
            (dr-to-rm dr-kitch-droom kitch)
            (connects dr-kitch-droom droom kitch)
            (connects dr-kitch-droom kitch droom)
            (dr-to-rm dr-hall-kitch kitch)
            (dr-to-rm dr-hall-kitch hall)
            (connects dr-hall-kitch kitch hall)
            (connects dr-hall-kitch hall kitch)
            (dr-to-rm dr-lroom-droom droom)
            (dr-to-rm dr-lroom-droom lroom)
            (connects dr-lroom-droom droom lroom)
            (connects dr-lroom-droom lroom droom)
            (dr-to-rm dr-den-droom lroom)
            (dr-to-rm dr-den-droom den)
            (connects dr-den-droom lroom den)
            (connects dr-den-droom den lroom)
            (dr-to-rm dr-den-kitch kitch)
            (dr-to-rm dr-den-kitch den)
            (connects dr-den-kitch kitch den)
            (connects dr-den-kitch den kitch)
            (dr-to-rm dr-den-bath bath)
            (dr-to-rm dr-den-bath den)
            (connects dr-den-bath bath den)
            (connects dr-den-bath den bath)
            (unlocked dr-kitch-droom)
            (dr-closed dr-kitch-droom)
            (unlocked dr-hall-kitch)
            (dr-open dr-hall-kitch)
            (unlocked dr-lroom-droom)
            (dr-closed dr-lroom-droom)
            (unlocked dr-den-droom)
            (dr-open dr-den-droom)
            (unlocked dr-den-kitch)
            (dr-closed dr-den-kitch)
            (unlocked dr-den-bath)
            (dr-open dr-den-bath)
            (is-room hall)
            (is-room kitch)
            (is-room droom)
            (is-room lroom)
            (is-room bath)
            (is-room den)
            (is-door dr-kitch-droom)
            (is-door dr-hall-kitch)
            (is-door dr-lroom-droom)
            (is-door dr-den-droom)
            (is-door dr-den-kitch)
            (is-door dr-den-bath)
            (pushable B)
            (carriable A)
            (is-object den-key)
            (is-object bath-key)
            (is-object B)
            (is-object A)
            (inroom B hall)
            (inroom A den)
            (inroom den-key bath)
            (inroom bath-key kitch)
            (inroom robot droom)
            (carriable den-key)
            (is-key dr-den-kitch den-key)
            (carriable bath-key)
            (is-key dr-den-bath bath-key)))
     (SS7-4 (and 
                (dr-open dr-lroom-droom)
                (dr-closed dr-den-kitch))
           ((arm-empty)
            (dr-to-rm dr-kitch-droom droom)
            (dr-to-rm dr-kitch-droom kitch)
            (connects dr-kitch-droom droom kitch)
            (connects dr-kitch-droom kitch droom)
            (dr-to-rm dr-hall-kitch kitch)
            (dr-to-rm dr-hall-kitch hall)
            (connects dr-hall-kitch kitch hall)
            (connects dr-hall-kitch hall kitch)
            (dr-to-rm dr-lroom-droom droom)
            (dr-to-rm dr-lroom-droom lroom)
            (connects dr-lroom-droom droom lroom)
            (connects dr-lroom-droom lroom droom)
            (dr-to-rm dr-den-droom lroom)
            (dr-to-rm dr-den-droom den)
            (connects dr-den-droom lroom den)
            (connects dr-den-droom den lroom)
            (dr-to-rm dr-den-kitch kitch)
            (dr-to-rm dr-den-kitch den)
            (connects dr-den-kitch kitch den)
            (connects dr-den-kitch den kitch)
            (dr-to-rm dr-den-bath bath)
            (dr-to-rm dr-den-bath den)
            (connects dr-den-bath bath den)
            (connects dr-den-bath den bath)
            (unlocked dr-kitch-droom)
            (dr-open dr-kitch-droom)
            (unlocked dr-hall-kitch)
            (dr-closed dr-hall-kitch)
            (unlocked dr-lroom-droom)
            (dr-open dr-lroom-droom)
            (unlocked dr-den-droom)
            (dr-closed dr-den-droom)
            (unlocked dr-den-kitch)
            (dr-open dr-den-kitch)
            (unlocked dr-den-bath)
            (dr-closed dr-den-bath)
            (is-room hall)
            (is-room kitch)
            (is-room droom)
            (is-room lroom)
            (is-room bath)
            (is-room den)
            (is-door dr-kitch-droom)
            (is-door dr-hall-kitch)
            (is-door dr-lroom-droom)
            (is-door dr-den-droom)
            (is-door dr-den-kitch)
            (is-door dr-den-bath)
            (pushable B)
            (is-object den-key)
            (is-object bath-key)
            (is-object B)
            (is-object A)
            (inroom B hall)
            (inroom A den)
            (inroom den-key bath)
            (inroom bath-key den)
            (inroom robot hall)
            (carriable den-key)
            (is-key dr-den-kitch den-key)
            (carriable bath-key)
            (is-key dr-den-bath bath-key)))
     (SS7-5 (and 
                (unlocked dr-den-droom)
                (locked dr-den-bath))
           ((arm-empty)
            (dr-to-rm dr-kitch-droom droom)
            (dr-to-rm dr-kitch-droom kitch)
            (connects dr-kitch-droom droom kitch)
            (connects dr-kitch-droom kitch droom)
            (dr-to-rm dr-hall-kitch kitch)
            (dr-to-rm dr-hall-kitch hall)
            (connects dr-hall-kitch kitch hall)
            (connects dr-hall-kitch hall kitch)
            (dr-to-rm dr-lroom-droom droom)
            (dr-to-rm dr-lroom-droom lroom)
            (connects dr-lroom-droom droom lroom)
            (connects dr-lroom-droom lroom droom)
            (dr-to-rm dr-den-droom lroom)
            (dr-to-rm dr-den-droom den)
            (connects dr-den-droom lroom den)
            (connects dr-den-droom den lroom)
            (dr-to-rm dr-den-kitch kitch)
            (dr-to-rm dr-den-kitch den)
            (connects dr-den-kitch kitch den)
            (connects dr-den-kitch den kitch)
            (dr-to-rm dr-den-bath bath)
            (dr-to-rm dr-den-bath den)
            (connects dr-den-bath bath den)
            (connects dr-den-bath den bath)
            (unlocked dr-kitch-droom)
            (dr-open dr-kitch-droom)
            (unlocked dr-hall-kitch)
            (dr-closed dr-hall-kitch)
            (unlocked dr-lroom-droom)
            (dr-open dr-lroom-droom)
            (unlocked dr-den-droom)
            (dr-closed dr-den-droom)
            (unlocked dr-den-kitch)
            (dr-open dr-den-kitch)
            (unlocked dr-den-bath)
            (dr-closed dr-den-bath)
            (is-room hall)
            (is-room kitch)
            (is-room droom)
            (is-room lroom)
            (is-room bath)
            (is-room den)
            (is-door dr-kitch-droom)
            (is-door dr-hall-kitch)
            (is-door dr-lroom-droom)
            (is-door dr-den-droom)
            (is-door dr-den-kitch)
            (is-door dr-den-bath)
            (pushable B)
            (is-object den-key)
            (is-object bath-key)
            (is-object B)
            (is-object A)
            (inroom B hall)
            (inroom A kitch)
            (inroom den-key hall)
            (inroom bath-key kitch)
            (inroom robot bath)
            (carriable den-key)
            (is-key dr-den-kitch den-key)
            (carriable bath-key)
            (is-key dr-den-bath bath-key)))
     (SS7-6 (and (next-to A C) (dr-closed dr-hall-kitch))
           ((arm-empty)
            (dr-to-rm dr-kitch-droom droom)
            (dr-to-rm dr-kitch-droom kitch)
            (connects dr-kitch-droom droom kitch)
            (connects dr-kitch-droom kitch droom)
            (dr-to-rm dr-hall-kitch kitch)
            (dr-to-rm dr-hall-kitch hall)
            (connects dr-hall-kitch kitch hall)
            (connects dr-hall-kitch hall kitch)
            (dr-to-rm dr-lroom-droom droom)
            (dr-to-rm dr-lroom-droom lroom)
            (connects dr-lroom-droom droom lroom)
            (connects dr-lroom-droom lroom droom)
            (dr-to-rm dr-den-droom lroom)
            (dr-to-rm dr-den-droom den)
            (connects dr-den-droom lroom den)
            (connects dr-den-droom den lroom)
            (dr-to-rm dr-den-kitch kitch)
            (dr-to-rm dr-den-kitch den)
            (connects dr-den-kitch kitch den)
            (connects dr-den-kitch den kitch)
            (dr-to-rm dr-den-bath bath)
            (dr-to-rm dr-den-bath den)
            (connects dr-den-bath bath den)
            (connects dr-den-bath den bath)
            (unlocked dr-kitch-droom)
            (dr-closed dr-kitch-droom)
            (unlocked dr-hall-kitch)
            (dr-open dr-hall-kitch)
            (unlocked dr-lroom-droom)
            (dr-closed dr-lroom-droom)
            (unlocked dr-den-droom)
            (dr-open dr-den-droom)
            (unlocked dr-den-kitch)
            (dr-closed dr-den-kitch)
            (unlocked dr-den-bath)
            (dr-open dr-den-bath)
            (is-room hall)
            (is-room kitch)
            (is-room droom)
            (is-room lroom)
            (is-room bath)
            (is-room den)
            (is-door dr-kitch-droom)
            (is-door dr-hall-kitch)
            (is-door dr-lroom-droom)
            (is-door dr-den-droom)
            (is-door dr-den-kitch)
            (is-door dr-den-bath)
            (pushable B)
            (carriable A)
            (is-object den-key)
            (is-object bath-key)
            (is-object C)
            (is-object B)
            (is-object A)
            (inroom C hall)
            (inroom B den)
            (inroom A hall)
            (inroom den-key lroom)
            (inroom bath-key bath)
            (inroom robot den)
            (carriable den-key)
            (is-key dr-den-kitch den-key)
            (carriable bath-key)
            (is-key dr-den-bath bath-key)))
     (SS7-7 (inroom bath-key lroom)
           ((arm-empty)
            (dr-to-rm dr-kitch-droom droom)
            (dr-to-rm dr-kitch-droom kitch)
            (connects dr-kitch-droom droom kitch)
            (connects dr-kitch-droom kitch droom)
            (dr-to-rm dr-hall-kitch kitch)
            (dr-to-rm dr-hall-kitch hall)
            (connects dr-hall-kitch kitch hall)
            (connects dr-hall-kitch hall kitch)
            (dr-to-rm dr-lroom-droom droom)
            (dr-to-rm dr-lroom-droom lroom)
            (connects dr-lroom-droom droom lroom)
            (connects dr-lroom-droom lroom droom)
            (dr-to-rm dr-den-droom lroom)
            (dr-to-rm dr-den-droom den)
            (connects dr-den-droom lroom den)
            (connects dr-den-droom den lroom)
            (dr-to-rm dr-den-kitch kitch)
            (dr-to-rm dr-den-kitch den)
            (connects dr-den-kitch kitch den)
            (connects dr-den-kitch den kitch)
            (dr-to-rm dr-den-bath bath)
            (dr-to-rm dr-den-bath den)
            (connects dr-den-bath bath den)
            (connects dr-den-bath den bath)
            (unlocked dr-kitch-droom)
            (dr-closed dr-kitch-droom)
            (unlocked dr-hall-kitch)
            (dr-open dr-hall-kitch)
            (unlocked dr-lroom-droom)
            (dr-closed dr-lroom-droom)
            (unlocked dr-den-droom)
            (dr-open dr-den-droom)
            (dr-closed dr-den-kitch)
            (locked dr-den-kitch)
            (unlocked dr-den-bath)
            (dr-closed dr-den-bath)
            (is-room hall)
            (is-room kitch)
            (is-room droom)
            (is-room lroom)
            (is-room bath)
            (is-room den)
            (is-door dr-kitch-droom)
            (is-door dr-hall-kitch)
            (is-door dr-lroom-droom)
            (is-door dr-den-droom)
            (is-door dr-den-kitch)
            (is-door dr-den-bath)
            (carriable C)
            (pushable A)
            (is-object den-key)
            (is-object bath-key)
            (is-object C)
            (is-object B)
            (is-object A)
            (inroom C hall)
            (inroom B den)
            (inroom A bath)
            (inroom den-key lroom)
            (inroom bath-key hall)
            (inroom robot den)
            (carriable den-key)
            (is-key dr-den-kitch den-key)
            (carriable bath-key)
            (is-key dr-den-bath bath-key)))))
