(load-goal '(and (shape E CYLINDRICAL)
                 (surface-condition E SMOOTH)
                 (surface-condition D SMOOTH)
                 (shape B CYLINDRICAL)
                 (joined B E ORIENTATION-1)
                 (surface-condition C POLISHED)))


(setq *END-TIME* 6)

(load-start-state
           '((last-time 6)
             (is-bolt (B1 (1.2 cm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (painted E (REGULAR RED))
             (temperature E COLD)
             (shape E UNDETERMINED)
             (is-object E)
             (surface-condition D POLISHED)
             (temperature D COLD)
             (shape D IRREGULAR)
             (is-object D)
             (has-hole C (1.4 cm) ORIENTATION-2)
             (temperature C COLD)
             (shape C UNDETERMINED)
             (is-object C)
             (has-hole B (1.2 cm) ORIENTATION-1)
             (has-hole E (1.2 cm) ORIENTATION-1)
             (painted B (REGULAR WHITE))
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (surface-condition A POLISHED)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
