(setq *TEST-PROBS*
    '((CC1-1 (and (surface-condition B SMOOTH)
                 (has-hole B (8 mm) ORIENTATION-1))
            ((last-time 3)
             (is-bolt (B1 (4 mm)))
             (is-bolt (B2 (1.4 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (4 mm) ORIENTATION-2)
             (painted B (REGULAR RED))
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (has-hole A (2 mm) ORIENTATION-3)
             (painted A (REGULAR WHITE))
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
     (CC1-2 (and (shape A CYLINDRICAL) (surface-condition A POLISHED))
            ((last-time 3)
             (is-bolt (B1 (8 mm)))
             (is-bolt (B2 (8 mm)))
             (last-scheduled A 0)
             (painted A (WATER-RES RED))
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC1-3 (and (has-hole B (2 mm) ORIENTATION-1)
                 (painted A (WATER-RES WHITE))
                 (shape B CYLINDRICAL))
            ((last-time 3)
             (is-bolt (B1 (6 mm)))
             (is-bolt (B2 (1.2 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (painted A (WATER-RES WHITE))
             (temperature A COLD)
             (shape A CYLINDRICAL)
             (is-object A)))
     (CC1-4 (and (shape B CYLINDRICAL)
                 (shape A CYLINDRICAL)
                 (painted A (REGULAR RED)))
            ((last-time 3)
             (is-bolt (B1 (1.4 cm)))
             (is-bolt (B2 (6 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B POLISHED)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC1-5 (and (joined A B ORIENTATION-4)
                 (painted B (WATER-RES WHITE))
                 (shape B CYLINDRICAL))
            ((last-time 3)
             (is-bolt (B1 (6 mm)))
             (is-bolt (B2 (6 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (6 mm) ORIENTATION-4)
             (temperature B COLD)
             (shape B CYLINDRICAL)
             (is-object B)
             (has-hole A (6 mm) ORIENTATION-4)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC1-6 (painted B (WATER-RES RED))
            ((last-time 3)
             (is-bolt (B1 (4 mm)))
             (is-bolt (B2 (2 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (2 mm) ORIENTATION-2)
             (painted B (REGULAR RED))
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (surface-condition A ROUGH)
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC1-7 (and (shape A CYLINDRICAL) (surface-condition B SMOOTH))
           ((last-time 3)
            (is-bolt (B1 (6 mm)))
            (is-bolt (B2 (1.4 cm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (surface-condition B SMOOTH)
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (has-hole A (4 mm) ORIENTATION-4)
            (temperature A COLD)
            (shape A IRREGULAR)
            (is-object A)))
     (CC1-8 (and (joined A B ORIENTATION-4) (shape A CYLINDRICAL))
           ((last-time 3)
            (is-bolt (B1 (2 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
	    (has-hole B (2 mm) ORIENTATION-4)
            (painted B (REGULAR WHITE))
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
	    (has-hole A (2 mm) ORIENTATION-4)
            (painted A (REGULAR RED))
            (temperature A COLD)
            (shape A UNDETERMINED)
            (is-object A)))
     (CC1-9 (and (has-hole B (1.2 cm) ORIENTATION-1) (shape A CYLINDRICAL))
           ((last-time 3)
            (is-bolt (B1 (1.2 cm)))
            (is-bolt (B2 (1 cm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (has-hole B (8 mm) ORIENTATION-2)
            (painted B (REGULAR RED))
            (temperature B COLD)
            (shape B UNDETERMINED)
            (is-object B)
            (painted A (WATER-RES RED))
            (temperature A COLD)
            (shape A IRREGULAR)
            (is-object A)))
     (CC1-10 (and (shape A CYLINDRICAL) (has-hole B (1.4 cm) ORIENTATION-4))
           ((last-time 3)
            (is-bolt (B1 (4 mm)))
            (is-bolt (B2 (2 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (has-hole B (6 mm) ORIENTATION-1)
            (temperature B COLD)
            (shape B UNDETERMINED)
            (is-object B)
            (painted A (WATER-RES RED))
            (surface-condition A SMOOTH)
            (temperature A COLD)
            (shape A CYLINDRICAL)
            (is-object A)))
     (CC1-11 (and (shape B CYLINDRICAL) (surface-condition B SMOOTH))
           ((last-time 3)
            (is-bolt (B1 (6 mm)))
            (is-bolt (B2 (8 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (temperature B COLD)
            (shape B IRREGULAR)
            (is-object B)
            (has-hole A (2 mm) ORIENTATION-2)
            (painted A (REGULAR RED))
            (surface-condition A ROUGH)
            (temperature A COLD)
            (shape A IRREGULAR)
            (is-object A)))))
