; 10 probs, 2 goals

(setq *TEST-PROBS*
    '((CC3-1 (and (joined A B ORIENTATION-2) (has-hole A (8 mm) ORIENTATION-1))
            ((last-time 3)
             (is-bolt (B1 (4 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (4 mm) ORIENTATION-2)
             (has-hole A (4 mm) ORIENTATION-2)
             (surface-condition B POLISHED)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (painted A (WATER-RES RED))
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC3-2 (and (joined A B ORIENTATION-2) (surface-condition A SMOOTH))
            ((last-time 3)
             (is-bolt (B1 (1.4 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (1.4 cm) ORIENTATION-2)
             (painted B (WATER-RES WHITE))
             (temperature B COLD)
             (shape B CYLINDRICAL)
             (is-object B)
             (painted A (REGULAR WHITE))
             (surface-condition A SMOOTH)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC3-3 (and (joined A B ORIENTATION-2) (painted B (REGULAR RED)))
            ((last-time 3)
             (is-bolt (B1 (1.4 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B SMOOTH)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (has-hole A (1.4 cm) ORIENTATION-2)
             (has-hole A (1.4 cm) ORIENTATION-2)
             (painted A (REGULAR RED))
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC3-4 (and (shape B CYLINDRICAL) (painted B (REGULAR RED)))
           ((last-time 3)
            (is-bolt (B1 (4 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (temperature A COLD)
            (shape A CYLINDRICAL)
            (is-object A)))
     (CC3-5 (and (surface-condition B SMOOTH)
                (shape B CYLINDRICAL))
           ((last-time 3)
            (is-bolt (B1 (2 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (has-hole B (4 mm) ORIENTATION-3)
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (has-hole A (8 mm) ORIENTATION-1)
            (temperature A COLD)
            (shape A UNDETERMINED)
            (is-object A)))
     (CC3-6 (and (joined A B ORIENTATION-3)
		  (has-hole A (1.2 cm) ORIENTATION-2))
           ((last-time 3)
            (is-bolt (B1 (1.4 cm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (painted B (REGULAR WHITE))
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (has-hole A (1.4 cm) ORIENTATION-3)
            (has-hole B (1.4 cm) ORIENTATION-3)
            (temperature A COLD)
            (shape A IRREGULAR)
            (is-object A)))
     (CC3-7 (and (has-hole A (1 cm) ORIENTATION-1)
                 (painted A (WATER-RES WHITE)))
           ((last-time 3)
            (is-bolt (B1 (8 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (has-hole B (6 mm) ORIENTATION-4)
            (painted B (WATER-RES WHITE))
            (surface-condition B ROUGH)
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (temperature A COLD)
            (shape A RECTANGULAR)
            (is-object A)))
     (CC3-8 (and (has-hole A (1 cm) ORIENTATION-1)
                (shape A CYLINDRICAL)
                (surface-condition A SMOOTH))
           ((last-time 3)
            (is-bolt (B1 (1 cm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (has-hole B (6 mm) ORIENTATION-4)
            (painted B (WATER-RES WHITE))
            (surface-condition B POLISHED)
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (has-hole A (1 cm) ORIENTATION-4)
            (temperature A COLD)
            (shape A IRREGULAR)
            (is-object A)))
     (CC3-9 (and (has-hole A (6 mm) ORIENTATION-1) (shape A CYLINDRICAL))
           ((last-time 3)
            (is-bolt (B1 (2 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (temperature A COLD)
            (shape A RECTANGULAR)
            (is-object A)))
     (CC3-10 (and (has-hole B (1 cm) ORIENTATION-4)
                (joined A B ORIENTATION-4))
           ((last-time 3)
            (is-bolt (B1 (8 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (surface-condition B SMOOTH)
            (temperature B COLD)
            (shape B CYLINDRICAL)
            (is-object B)
            (has-hole A (8 mm) ORIENTATION-4)
            (temperature A COLD)
            (shape A UNDETERMINED)
            (is-object A)))))
