; 10 probs, max 3 goals 
(setq *TEST-PROBS*
    '((CC5-0 (and (joined A B ORIENTATION-4) (surface-condition A POLISHED))
            ((last-time 3)
             (is-bolt (B1 (4 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (8 mm) ORIENTATION-2)
             (temperature B COLD)
             (shape B CYLINDRICAL)
             (is-object B)
	     (has-hole B (4 mm) ORIENTATION-4)
             (painted A (REGULAR RED))
             (surface-condition A SMOOTH)
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
(CC5-1 (and (joined A B ORIENTATION-2)
		 (has-hole A (4 mm) ORIENTATION-1)
                 (surface-condition A POLISHED))
            ((last-time 4)
             (is-bolt (B1 (8 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (6 mm) ORIENTATION-4)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (has-hole A (1.4 cm) ORIENTATION-2)
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
     (CC5-2 (and (has-hole B (1.2 cm) ORIENTATION-1)
                 (surface-condition B SMOOTH))
            ((last-time 4)
             (is-bolt (B1 (4 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (4 mm) ORIENTATION-3)
             (painted B (REGULAR WHITE))
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
     (CC5-3 (and (joined A B ORIENTATION-2) (painted B (REGULAR RED)))
            ((last-time 4)
             (is-bolt (B1 (6 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B POLISHED)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC5-4 (and (joined A B ORIENTATION-4)
                 (shape A CYLINDRICAL))
            ((last-time 3)
             (is-bolt (B1 (2 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (has-hole B (2 mm) ORIENTATION-4)
             (painted A (REGULAR RED))
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC5-5 (and (joined A B ORIENTATION-2) (painted A (WATER-RES RED)))
            ((last-time 4)
             (is-bolt (B1 (1.4 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B SMOOTH)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC5-6 (and (joined A B ORIENTATION-3)(has-hole A (4 mm) ORIENTATION-2))
            ((last-time 4)
             (is-bolt (B1 (6 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature B COLD)
             (shape B CYLINDRICAL)
             (is-object B)
             (has-hole A (2 mm) ORIENTATION-1)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC5-7 (and (surface-condition B POLISHED)
		 (has-hole B (6 mm) ORIENTATION-4))
            ((last-time 3)
             (is-bolt (B1 (2 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (2 mm) ORIENTATION-2)
             (painted B (REGULAR RED))
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (surface-condition A ROUGH)
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC5-8  (and (painted A (REGULAR RED)) (surface-condition A SMOOTH))
           ((last-time 3)
            (is-bolt (B1 (8 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (painted B (REGULAR WHITE))
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (temperature A COLD)
            (shape A UNDETERMINED)
            (is-object A)))
     (CC5-9 (and (shape B CYLINDRICAL) (painted B (REGULAR RED)))
           ((last-time 3)
            (is-bolt (B1 (1.4 cm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (surface-condition B ROUGH)
            (temperature B COLD)
            (shape B RECTANGULAR)
            (is-object B)
            (temperature A COLD)
            (shape A RECTANGULAR)
            (is-object A)))
     (CC5-10 (and (painted B (WATER-RES RED))
                (surface-condition B SMOOTH)
                (shape B CYLINDRICAL))
           ((last-time 3)
            (is-bolt (B1 (2 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (temperature B COLD)
            (shape B UNDETERMINED)
            (is-object B)
            (temperature A COLD)
            (shape A UNDETERMINED)
            (is-object A)))))
