; 11 probs, 3 goals
(setq *TEST-PROBS*
    '((CC6-1 (and (shape B CYLINDRICAL) (surface-condition B POLISHED))
            ((last-time 3)
             (is-bolt (B1 (6 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (6 mm) ORIENTATION-3)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (has-hole A (6 mm) ORIENTATION-1)
             (painted A (WATER-RES RED))
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC6-2 (and (shape B CYLINDRICAL)
                 (shape A CYLINDRICAL)
                 (joined A B ORIENTATION-3))
            ((last-time 3)
             (is-bolt (B1 (8 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B SMOOTH)
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (surface-condition A ROUGH)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC6-3 (and (surface-condition B SMOOTH)
                 (painted B (WATER-RES RED)))
            ((last-time 4)
             (is-bolt (B1 (1.4 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (painted B (WATER-RES RED))
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC6-4 (and (surface-condition B POLISHED)
                 (shape B CYLINDRICAL)
;                 (has-hole B (1.4 cm) ORIENTATION-3)
	    )
            ((last-time 3)
             (is-bolt (B1 (4 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC6-5 (and (joined A B ORIENTATION-2)
                 (surface-condition B POLISHED))
            ((last-time 3)
             (is-bolt (B1 (4 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (painted B (REGULAR RED))
	     (has-hole A (4 mm) ORIENTATION-2)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC6-6 (and (has-hole B (6 mm) ORIENTATION-1)
		 (shape B CYLINDRICAL))
            ((last-time 3)
             (is-bolt (B1 (8 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B ROUGH)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (surface-condition A ROUGH)
             (temperature A COLD)
             (shape A CYLINDRICAL)
             (is-object A)))
     (CC6-7 (and (shape B CYLINDRICAL) (has-hole B (2 mm) ORIENTATION-2))
            ((last-time 3)
             (is-bolt (B1 (2 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B ROUGH)
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (has-hole A (8 mm) ORIENTATION-4)
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC6-8 (and (joined A B ORIENTATION-4) (painted B (WATER-RES WHITE)))
            ((last-time 3)
             (is-bolt (B1 (6 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (1.4 cm) ORIENTATION-2)
             (painted B (REGULAR RED))
             (surface-condition B SMOOTH)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (has-hole A (1 cm) ORIENTATION-2)
             (painted A (REGULAR RED))
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC6-9 (and (joined A B ORIENTATION-3)(has-hole A (4 mm) ORIENTATION-2))
            ((last-time 3)
             (is-bolt (B1 (1 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (1.4 cm) ORIENTATION-1)
             (painted B (WATER-RES RED))
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (has-hole A (8 mm) ORIENTATION-2)
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
     (CC6-10 (and (joined A B ORIENTATION-4) (painted A (REGULAR WHITE)))
            ((last-time 3)
             (is-bolt (B1 (1.4 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (4 mm) ORIENTATION-2)
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (painted A (REGULAR RED))
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC6-11 (and (joined A B ORIENTATION-3) (painted A (REGULAR WHITE)))
            ((last-time 3)
             (is-bolt (B1 (1.2 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (4 mm) ORIENTATION-2)
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (painted A (REGULAR RED))
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))))
