; 10 probs, max 4 goals
(setq *TEST-PROBS*
   '((CC7-1 (and (joined A B ORIENTATION-4)
		 (shape A CYLINDRICAL)
                 (has-hole B (8 mm) ORIENTATION-4))
            ((last-time 4)
             (is-bolt (B1 (1 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B POLISHED)
             (temperature B COLD)
             (shape B CYLINDRICAL)
             (is-object B)
             (surface-condition A POLISHED)
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
     (CC7-2 (and (painted A (REGULAR WHITE))
                 (painted B (WATER-RES WHITE))
                 (shape B CYLINDRICAL))
            ((last-time 3)
             (is-bolt (B1 (1 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (has-hole A (2 mm) ORIENTATION-1)
             (painted A (WATER-RES RED))
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC7-3 (and (painted B (WATER-RES RED))
                 (shape B CYLINDRICAL))
            ((last-time 3)
             (is-bolt (B1 (1.4 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (painted B (WATER-RES RED))
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (has-hole A (1.4 cm) ORIENTATION-2)
             (painted A (REGULAR RED))
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC7-4 (and (painted A (REGULAR WHITE))
                 (surface-condition A POLISHED)
                 (has-hole A (2 mm) ORIENTATION-3))
            ((last-time 3)
             (is-bolt (B1 (1.4 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (1.4 cm) ORIENTATION-2)
             (painted B (REGULAR RED))
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC7-5 (and (joined A B ORIENTATION-1) (surface-condition B POLISHED))
            ((last-time 3)
             (is-bolt (B1 (1 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (painted B (WATER-RES RED))
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (painted A (WATER-RES WHITE))
             (temperature A COLD)
             (shape A CYLINDRICAL)
             (is-object A)))
     (CC7-6 (and (surface-condition B POLISHED)
                 (shape A CYLINDRICAL)
                 (shape B CYLINDRICAL)
                 (surface-condition A SMOOTH))
            ((last-time 3)
             (is-bolt (B1 (8 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC7-7a (and (joined B A ORIENTATION-4)
                 (painted A (REGULAR WHITE))
                 (shape B CYLINDRICAL))
            ((last-time 3)
             (is-bolt (B1 (1.2 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (2 mm) ORIENTATION-2)
             (painted B (REGULAR RED))
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (painted A (WATER-RES RED))
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC7-7b (and (joined A B ORIENTATION-4)
                 (painted A (REGULAR WHITE))
                 (shape B CYLINDRICAL))
            ((last-time 3)
             (is-bolt (B1 (1.2 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (2 mm) ORIENTATION-2)
             (painted B (REGULAR RED))
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (painted A (WATER-RES RED))
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC7-8 (and 
                 (surface-condition B POLISHED)
                 (shape B CYLINDRICAL)
                 (joined A B ORIENTATION-1))
            ((last-time 3)
             (is-bolt (B1 (2 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (surface-condition A ROUGH)
             (temperature A COLD)
             (shape A IRREGULAR)
             (is-object A)))
     (CC7-9 (and (surface-condition B SMOOTH)
                 (painted A (WATER-RES WHITE))
                 (painted B (WATER-RES RED))
                 (has-hole A (1.2 cm) ORIENTATION-4))
            ((last-time 3)
             (is-bolt (B1 (1 cm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole B (4 mm) ORIENTATION-3)
             (temperature B COLD)
             (shape B CYLINDRICAL)
             (is-object B)
             (has-hole A (1.2 cm) ORIENTATION-1)
             (painted A (WATER-RES RED))
             (surface-condition A SMOOTH)
             (temperature A COLD)
             (shape A CYLINDRICAL)
             (is-object A)))
     (CC7-10 (and (joined A B ORIENTATION-4)
                 (shape B CYLINDRICAL)
                 (painted B (WATER-RES WHITE)))
            ((last-time 4)
             (is-bolt (B1 (8 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition B POLISHED)
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (painted A (REGULAR RED))
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))))
