; 10 problems 6-8 goals? 5 objs.
(setq *TEST-PROBS*
    '((CC8-1 (and (painted D (WATER-RES WHITE))
		 (painted E (WATER-RES WHITE))
		 (painted A (WATER-RES WHITE))
                 (painted C (REGULAR WHITE)))
            ((last-time 6)
             (is-bolt (B1 (4 mm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole E (1.2 cm) ORIENTATION-2)
             (temperature E COLD)
             (shape E RECTANGULAR)
             (is-object E)
             (painted D (REGULAR RED))
             (temperature D COLD)
             (shape D UNDETERMINED)
             (is-object D)
             (temperature C COLD)
             (shape C UNDETERMINED)
             (is-object C)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (has-hole A (1 cm) ORIENTATION-3)
             (temperature A COLD)
             (shape A CYLINDRICAL)
             (is-object A)))
(CC8-2 (and (shape D CYLINDRICAL)
                 (shape C CYLINDRICAL)
                 (shape A CYLINDRICAL)
                 (has-hole A (8 mm) ORIENTATION-4))
            ((last-time 8)
             (is-bolt (B1 (8 mm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole E (2 mm) ORIENTATION-3)
             (painted E (REGULAR WHITE))
             (temperature E COLD)
             (shape E RECTANGULAR)
             (is-object E)
             (surface-condition D SMOOTH)
             (temperature D COLD)
             (shape D UNDETERMINED)
             (is-object D)
             (has-hole C (4 mm) ORIENTATION-3)
             (surface-condition C POLISHED)
             (temperature C COLD)
             (shape C RECTANGULAR)
             (is-object C)
             (has-hole B (1 cm) ORIENTATION-4)
             (temperature B COLD)
             (shape B IRREGULAR)
             (is-object B)
             (painted A (WATER-RES WHITE))
             (surface-condition A SMOOTH)
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
     (CC8-3 (and (surface-condition A SMOOTH)
                 (shape A CYLINDRICAL)
		 (painted D (REGULAR RED))
                 (shape D CYLINDRICAL))
            ((last-time 6)
             (is-bolt (B1 (2 mm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (painted E (WATER-RES RED))
             (surface-condition E ROUGH)
             (temperature E COLD)
             (shape E CYLINDRICAL)
             (is-object E)
             (has-hole D (6 mm) ORIENTATION-1)
             (surface-condition D POLISHED)
             (temperature D COLD)
             (shape D IRREGULAR)
             (is-object D)
             (has-hole C (1 cm) ORIENTATION-2)
             (surface-condition C SMOOTH)
             (temperature C COLD)
             (shape C UNDETERMINED)
             (is-object C)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (has-hole A (1.2 cm) ORIENTATION-3)
             (surface-condition A SMOOTH)
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
     (CC8-4 (and (painted E (WATER-RES RED))
                 (shape C CYLINDRICAL)
                 (has-hole E (6 mm) ORIENTATION-1)
                 (has-hole A (1 cm) ORIENTATION-1))
            ((last-time 6)
             (is-bolt (B1 (6 mm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature E COLD)
             (shape E RECTANGULAR)
             (is-object E)
             (temperature D COLD)
             (shape D RECTANGULAR)
             (is-object D)
             (has-hole C (1.4 cm) ORIENTATION-4)
             (temperature C COLD)
             (shape C IRREGULAR)
             (is-object C)
             (has-hole B (1.2 cm) ORIENTATION-2)
             (surface-condition B SMOOTH)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (has-hole A (4 mm) ORIENTATION-3)
             (temperature A COLD)
             (shape A CYLINDRICAL)
             (is-object A)))
     (CC8-5 (and (joined A D ORIENTATION-4)
                 (surface-condition D POLISHED)
                 (painted A (REGULAR RED))
                 (painted D (WATER-RES WHITE))
                 (shape A CYLINDRICAL))
            ((last-time 6)
             (is-bolt (B1 (1 cm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition E ROUGH)
             (temperature E COLD)
             (shape E RECTANGULAR)
             (is-object E)
             (painted D (REGULAR RED))
             (surface-condition D POLISHED)
             (temperature D COLD)
             (shape D IRREGULAR)
             (is-object D)
             (has-hole C (8 mm) ORIENTATION-2)
             (painted C (REGULAR RED))
             (temperature C COLD)
             (shape C UNDETERMINED)
             (is-object C)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC8-6 (and (painted E (REGULAR WHITE))
                 (joined E D ORIENTATION-1))
            ((last-time 4)
             (is-bolt (B1 (4 mm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (has-hole E (4 mm) ORIENTATION-1)
             (painted E (REGULAR RED))
             (temperature E COLD)
             (shape E UNDETERMINED)
             (is-object E)
             (painted D (WATER-RES RED))
             (temperature D COLD)
             (shape D IRREGULAR)
             (is-object D)
             (has-hole C (1.2 cm) ORIENTATION-2)
             (surface-condition C ROUGH)
             (temperature C COLD)
             (shape C UNDETERMINED)
             (is-object C)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC8-7 (and (shape B CYLINDRICAL)
                 (shape E CYLINDRICAL)
                 (joined A E ORIENTATION-1))
            ((last-time 6)
             (is-bolt (B1 (1 cm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (surface-condition E ROUGH)
             (temperature E COLD)
             (shape E RECTANGULAR)
             (is-object E)
             (painted D (REGULAR WHITE))
             (temperature D COLD)
             (shape D RECTANGULAR)
             (is-object D)
             (surface-condition C POLISHED)
             (temperature C COLD)
             (shape C UNDETERMINED)
             (is-object C)
             (has-hole B (1.4 cm) ORIENTATION-3)
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (surface-condition A SMOOTH)
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
     (CC8-8 (and (shape E CYLINDRICAL)
                 (surface-condition E SMOOTH)
                 (surface-condition D SMOOTH)
                 (joined B E ORIENTATION-1)
                 (shape B CYLINDRICAL)
                 (surface-condition C POLISHED)
                 (joined D E ORIENTATION-1)
                 (painted A (WATER-RES RED)))
            ((last-time 6)
             (is-bolt (B1 (1.2 cm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (painted E (REGULAR RED))
             (temperature E COLD)
             (shape E UNDETERMINED)
             (is-object E)
             (surface-condition D POLISHED)
             (temperature D COLD)
             (shape D IRREGULAR)
             (is-object D)
             (has-hole C (1.4 cm) ORIENTATION-2)
             (surface-condition C POLISHED)
             (temperature C COLD)
             (shape C UNDETERMINED)
             (is-object C)
             (has-hole B (1.2 cm) ORIENTATION-3)
             (painted B (REGULAR WHITE))
             (temperature B COLD)
             (shape B RECTANGULAR)
             (is-object B)
             (surface-condition A POLISHED)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
     (CC8-9 (and (has-hole D (6 mm) ORIENTATION-1)
                 (has-hole E (1.4 cm) ORIENTATION-3)
                 (joined A E ORIENTATION-1)
                 (shape C CYLINDRICAL)
                 (surface-condition E POLISHED)
                 (has-hole C (1.4 cm) ORIENTATION-3)
                 (shape D CYLINDRICAL))
            ((last-time 6)
             (is-bolt (B1 (2 mm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature E COLD)
             (shape E IRREGULAR)
             (is-object E)
             (painted D (WATER-RES WHITE))
             (temperature D COLD)
             (shape D CYLINDRICAL)
             (is-object D)
             (has-hole C (8 mm) ORIENTATION-1)
             (surface-condition C ROUGH)
             (temperature C COLD)
             (shape C IRREGULAR)
             (is-object C)
             (surface-condition B SMOOTH)
             (temperature B COLD)
             (shape B CYLINDRICAL)
             (is-object B)
             (surface-condition A SMOOTH)
             (temperature A COLD)
             (shape A RECTANGULAR)
             (is-object A)))
; cant believe it joined comes first!
;     (CC8-11 (and (surface-condition E SMOOTH)
;                 (has-hole E (4 mm) ORIENTATION-1)
;                 (shape E CYLINDRICAL)
;                 (joined D E ORIENTATION-1)))
     (CC8-10 (and
                 (shape E CYLINDRICAL)
                 (joined D E ORIENTATION-1))
            ((last-time 6)
             (is-bolt (B1 (4 mm)))
             (last-scheduled E 0)
             (last-scheduled D 0)
             (last-scheduled C 0)
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature E COLD)
             (shape E RECTANGULAR)
             (is-object E)
             (temperature D COLD)
             (shape D RECTANGULAR)
             (is-object D)
             (temperature C COLD)
             (shape C RECTANGULAR)
             (is-object C)
             (surface-condition B ROUGH)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))))
