(setq *TEST-PROBS*
    '((CPROB9-96 (has-hole A (1.2 cm) ORIENTATION-1)
            ((last-time 26)
             (is-bolt (B1 (1 cm)))
             (is-bolt (B2 (4 mm)))
             (last-scheduled B 0)
             (last-scheduled A 0)
             (temperature B COLD)
             (shape B UNDETERMINED)
             (is-object B)
             (temperature A COLD)
             (shape A UNDETERMINED)
             (is-object A)))
    (CPROB9-98 (and (shape B CYLINDRICAL) (has-hole A (1.2 cm) ORIENTATION-2))
           ((last-time 26)
            (is-bolt (B1 (6 mm)))
            (is-bolt (B2 (2 mm)))
            (last-scheduled B 0)
            (last-scheduled A 0)
            (has-hole B (1.4 cm) ORIENTATION-4)
            (painted B (WATER-RES WHITE))
            (temperature B COLD)
            (shape B CYLINDRICAL)
            (is-object B)
            (surface-condition A POLISHED)
            (temperature A COLD)
            (shape A RECTANGULAR)
            (is-object A)))
    (CPROB9-106 (and (painted A (REGULAR WHITE))
                  (has-hole B (1 cm) ORIENTATION-4))
             ((last-time 7)
              (is-bolt (B1 (1.4 cm)))
              (is-bolt (B2 (1 cm)))
              (last-scheduled B 0)
              (last-scheduled A 0)
              (has-hole B (1.2 cm) ORIENTATION-1)
              (painted B (WATER-RES RED))
              (temperature B COLD)
              (shape B IRREGULAR)
              (is-object B)
              (has-hole A (1.2 cm) ORIENTATION-2)
              (painted A (REGULAR RED))
              (surface-condition A POLISHED)
              (temperature A COLD)
              (shape A IRREGULAR)
              (is-object A)))))
