FROM java:8-jre
MAINTAINER Chao Ji <17212010013@fudan.edu.cn>

ADD ./target/ts-ticket-advance-service-1.0.jar /app/
CMD ["java", "-Xmx200m", "-jar", "/app/ts-ticket-advance-service-1.0.jar"]

EXPOSE 14321