#!/bin/bash

for (( rs = 1; rs < 3; rs++ )); do
  echo "Intializing replica ${rs} set"
  replicate="rs.initiate(); sleep(1000); cfg = rs.conf(); cfg.members[0].host = \"dockermongocluster_mongors${rs}n1_1\"; rs.reconfig(cfg); rs.add(\"dockermongocluster_mongors${rs}n2_1\"); rs.add(\"dockermongocluster_mongors${rs}n3_1\"); rs.status();"
  docker exec -it dockermongocluster_mongors${rs}n1_1 bash -c "echo '${replicate}' | mongo"
done

sleep 2
# Add better mechanisum to wait for mongos connectivity to be
# established by tailing docker log for connection readiness

docker exec -it dockermongocluster_mongos1_1 bash -c "echo \"sh.addShard('mongors1/dockermongocluster_mongors1n1_1:27017'); sh.addShard('mongors2/dockermongocluster_mongors2n1_1:27017');\" | mongo "
