
(load-goal '(and (inroom robot rm2) (next-to b1 b2)))
; '(and (inroom robot rm2)

(load-start-state 
    '((arm-empty)
      (inroom robot rm1)
      (pushable b1)
      (pushable b2)
      (inroom b1 rm1)
      (inroom b2 rm1)
      (is-object b1)
      (is-object b2)
      (is-room rm1)
      (is-room rm2)
      (is-door dr12)
      (dr-to-rm dr12 rm1)
      (dr-to-rm dr12 rm2)
      (connects dr12 rm1 rm2)
      (connects dr12 rm2 rm1)
      (dr-open dr12)))
