(load-goal '(in-room box1 rram))

(load-start-state
 '((is-type drramrclk door)
;   (is-type drclkrpdp door)
   (is-type rclk room)
   (is-type rram room)
;   (is-type rpdp room)
   (is-type box1 box)
   (is-type robot1 robot)
;   (is-type robot2 robot)
   (connects drramrclk rclk rram)   
   (connects drramrclk rram rclk)
;   (connect drclkrpdp rclk rpdp)
;   (connect drclkrpdp rpdp rclk)
   (statis drramrclk open)
;   (statis drclkrpdp open)
   (pushable box1)
   (weight box1 50)
   (in-room box1 rclk)
   (in-room robot1 rclk)
;   (in-room robot2 rclk)
   (next-to robot1 box1)
;   (next-to robot2 box1)
   (next-to robot1 drramrclk)
;   (next-to robot2 drramrclk)
   (next-to box1 drramrclk)

   ))
