(load-goal '(in-room box1 rram))

(load-start-state
 '((is-type drramrclk door)
   (is-type drclkrpdp door)
   (is-type rclk room)
   (is-type rram room)
   (is-type rpdp room)
   (is-type box1 box)
   (is-type box2 box)
   (is-type block1 block)
   (is-type robot1 robot)
   (is-type robot2 robot)
   (connects drramrclk rclk rram)   ;connect does not work
   (connects drramrclk rram rclk)
   (connects drclkrpdp rclk rpdp)
   (connects drclkrpdp rpdp rclk)
   (statis drramrclk open)
   (statis drclkrpdp open)
   (pushable box1)
   (pushable block1)
   (in box2 block1)
   (weight box1 50)
   (weight box2 200)
   (weight block1 50)
   (in-room box1 rclk)
   (in-room box2 rclk)
   (in-room block1 rclk)
   (in-room robot1 rclk)
   (in-room robot2 rclk)
   (next-to robot1 box1)
   (next-to robot2 box1)
   ))
