
(load-goal '(statis dramhal open))

(load-start-state
  '((connect dunimys runi rmys)
    (connect dmysram rmys rram)
    (connect dramhal rram rhal)
    (connect dmyspdp rmys rpdp)
    (connect dpdpclk rpdp rclk)
    (connect dmysclk rmys rclk)
    (connect dramclk rram rclk)
    (connect dclkril rclk rril)
;    (connect dunimys rmys runi)
;    (connect dmysram rram rmys)
;    (connect dramhal rhal rram)
;    (connect dmyspdp rpdp rmys)
;    (connect dpdpclk rclk rpdp)
;    (connect dmysclk rclk rmys)
;    (connect dramclk rclk rram)
;    (connect dclkril rril rclk)
    (statis dunimys open)
    (statis dmysram open)
    (statis dramhal locked)
    (statis dmyspdp open)
    (statis dpdpclk open)
    (statis dmysclk open)
    (statis dramclk closed)
    (statis dclkril closed)
    (is-type dunimys door)
    (is-type dmysram door)
    (is-type dramhal door)
    (is-type dmyspdp door)
    (is-type dpdpclk door)
    (is-type dmysclk door)
    (is-type dramclk door)
    (is-type dclkril door)
    (is-type runi room)
    (is-type rmys room)
    (is-type rram room)
    (is-type rhal room)
    (is-type rpdp room)
    (is-type rclk room)
    (is-type rril room)
    (is-type box1 box)
    (is-type box2 box)
    (is-type box3 box)
    (is-type robot robot)
    (in-room robot rram)
    (in-room box1 rpdp)
    (in-room box2 rpdp)
    (in-room box3 rclk)
    (pushable box1)
    (pushable box2)
    (pushable box3)
    (is-type keys key)
    (is-key dramhal keys)
    (next-to dramhal keys)
    (in-room keys rram)))
    
