(load-goal '(in box1 block1))

(load-start-state
 '((connects drramrclk rclk rram)     ;order does not matter
   (connects drramrclk rram rclk)
   (connects drclkrpdp rclk rpdp)
   (connects drclkrpdp rpdp rclk)
   (statis drramrclk open)
   (statis drclkrpdp open)
   (is-type drramrclk door)
   (is-type drclkrpdp door)
   (is-type rclk room)
   (is-type rram room)
   (is-type rpdp room)
   (is-type box1 box)
   (is-type box2 box)
   (is-type block1 block)
   (is-type robot1 robot)
   (is-type robot2 robot)
   (in-room box1 rclk)
   (in-room box2 rclk)
   (in-room block1 rclk)
   (in-room robot1 rclk)
   (in-room robot2 rram)
   (pushable box1)
   (pushable block1) ;   (in box2 block1)
   (weight box1 200)
   (weight box2 200)
   (weight block1 50)))
