(load-goal '(next-to box1 block1))
		 

(load-start-state
 '(
;   (connect drramrclk rram rclk)    
;   (connect drclkrpdp rpdp rclk)
   (connect drramrclk rclk rram)
   (connect drclkrpdp rclk rpdp)
   (statis drramrclk open)  ;*******
   (statis drclkrpdp open)
   (is-type drramrclk door)
   (is-type drclkrpdp door)
   (is-type rclk room)
   (is-type rram room)
   (is-type rpdp room)
   (is-type box1 box)
   (is-type block1 block)
   (is-type robot1 robot)
   (is-type robot2 robot)
   (is-type key1 key)
   (is-key  drramrclk key1)
   (in-room box1 rclk)
   (in-room block1 rclk)
   (in-room robot1 rclk)
   (in-room robot2 rram)
   (next-to robot2 key1)
   (pushable box1)
   (pushable block1)
   (weight box1 200)
   (weight block1 200)))
