% enlist(student,Service).
% student is enlisted in Service.

enlist(student40,fire_department).
enlist(student51,fire_department).
enlist(student109,fire_department).
enlist(student139,fire_department).
enlist(student148,fire_department).
enlist(student167,fire_department).
enlist(student168,fire_department).
enlist(student183,fire_department).
enlist(student211,fire_department).
enlist(student224,fire_department).
enlist(student233,fire_department).
enlist(student241,fire_department).
enlist(student262,fire_department).
enlist(student267,fire_department).
enlist(student280,fire_department).
enlist(student286,fire_department).
enlist(student288,fire_department).
enlist(student304,fire_department).
enlist(student313,fire_department).
enlist(student328,fire_department).
enlist(student329,fire_department).
enlist(student340,fire_department).
enlist(student349,fire_department).
enlist(student372,fire_department).
enlist(student404,fire_department).
enlist(student423,fire_department).
enlist(student428,fire_department).
enlist(student458,fire_department).
enlist(student474,fire_department).
enlist(student500,fire_department).
enlist(student539,fire_department).
enlist(student560,fire_department).
enlist(student562,fire_department).
enlist(student568,fire_department).
enlist(student585,fire_department).
enlist(student613,fire_department).
enlist(student634,fire_department).
enlist(student647,fire_department).
enlist(student668,fire_department).
enlist(student674,fire_department).
enlist(student702,fire_department).
enlist(student714,fire_department).
enlist(student758,fire_department).
enlist(student764,fire_department).
enlist(student768,fire_department).
enlist(student807,fire_department).
enlist(student854,fire_department).
enlist(student888,fire_department).
enlist(student908,fire_department).
enlist(student985,fire_department).
enlist(student35,fire_department).
enlist(student53,fire_department).
enlist(student160,fire_department).
enlist(student161,fire_department).
enlist(student201,fire_department).
enlist(student252,fire_department).
enlist(student287,fire_department).
enlist(student298,fire_department).
enlist(student310,fire_department).
enlist(student321,fire_department).
enlist(student325,fire_department).
enlist(student375,fire_department).
enlist(student424,fire_department).
enlist(student455,fire_department).
enlist(student462,fire_department).
enlist(student514,fire_department).
enlist(student528,fire_department).
enlist(student540,fire_department).
enlist(student566,fire_department).
enlist(student683,fire_department).
enlist(student715,fire_department).
enlist(student771,fire_department).
enlist(student839,fire_department).
enlist(student865,fire_department).
enlist(student876,fire_department).
enlist(student880,fire_department).
enlist(student931,fire_department).
enlist(student939,fire_department).
enlist(student1000,air_force).
enlist(student999,fire_department).
enlist(student996,navy).
enlist(student993,fire_department).
enlist(student992,marines).
enlist(student985,navy).
enlist(student981,air_force).
enlist(student980,fire_department).
enlist(student977,foreign_legion).
enlist(student975,army).
enlist(student962,marines).
enlist(student959,air_force).
enlist(student956,army).
enlist(student955,marines).
enlist(student952,navy).
enlist(student948,air_force).
enlist(student946,navy).
enlist(student942,air_force).
enlist(student937,navy).
enlist(student925,fire_department).
enlist(student915,army).
enlist(student913,air_force).
enlist(student905,air_force).
enlist(student902,army).
enlist(student895,fire_department).
enlist(student894,marines).
enlist(student889,foreign_legion).
enlist(student876,foreign_legion).
enlist(student875,foreign_legion).
enlist(student866,foreign_legion).
enlist(student856,army).
enlist(student854,fire_department).
enlist(student844,fire_department).
enlist(student840,navy).
enlist(student839,foreign_legion).
enlist(student836,navy).
enlist(student835,navy).
enlist(student832,peace_corps).
enlist(student831,marines).
enlist(student817,marines).
enlist(student815,fire_department).
enlist(student808,air_force).
enlist(student804,navy).
enlist(student803,fire_department).
enlist(student795,navy).
enlist(student794,air_force).
enlist(student793,foreign_legion).
enlist(student790,fire_department).
enlist(student789,army).
enlist(student779,navy).
enlist(student770,peace_corps).
enlist(student765,marines).
enlist(student763,fire_department).
enlist(student751,navy).
enlist(student750,air_force).
enlist(student748,air_force).
enlist(student738,fire_department).
enlist(student735,air_force).
enlist(student733,navy).
enlist(student729,army).
enlist(student724,marines).
enlist(student722,foreign_legion).
enlist(student721,peace_corps).
enlist(student714,army).
enlist(student712,fire_department).
enlist(student708,foreign_legion).
enlist(student705,fire_department).
enlist(student701,peace_corps).
enlist(student699,air_force).
enlist(student697,marines).
enlist(student696,peace_corps).
enlist(student694,fire_department).
enlist(student684,foreign_legion).
enlist(student681,foreign_legion).
enlist(student680,navy).
enlist(student678,foreign_legion).
enlist(student676,peace_corps).
enlist(student670,air_force).
enlist(student664,army).
enlist(student663,peace_corps).
enlist(student662,marines).
enlist(student660,army).
enlist(student652,navy).
enlist(student646,marines).
enlist(student637,fire_department).
enlist(student634,army).
enlist(student633,foreign_legion).
enlist(student628,army).
enlist(student621,peace_corps).
enlist(student618,foreign_legion).
enlist(student617,foreign_legion).
enlist(student616,navy).
enlist(student611,army).
enlist(student609,peace_corps).
enlist(student605,air_force).
enlist(student604,foreign_legion).
enlist(student596,peace_corps).
enlist(student595,marines).
enlist(student593,army).
enlist(student589,peace_corps).
enlist(student587,marines).
enlist(student569,peace_corps).
enlist(student568,army).
enlist(student562,marines).
enlist(student550,fire_department).
enlist(student548,foreign_legion).
enlist(student546,air_force).
enlist(student544,peace_corps).
enlist(student543,foreign_legion).
enlist(student542,fire_department).
enlist(student539,army).
enlist(student536,marines).
enlist(student531,foreign_legion).
enlist(student527,peace_corps).
enlist(student511,navy).
enlist(student507,fire_department).
enlist(student504,air_force).
enlist(student496,navy).
enlist(student494,peace_corps).
enlist(student493,marines).
enlist(student480,peace_corps).
enlist(student467,navy).
enlist(student458,peace_corps).
enlist(student450,peace_corps).
enlist(student448,fire_department).
enlist(student443,navy).
enlist(student442,navy).
enlist(student441,peace_corps).
enlist(student437,fire_department).
enlist(student420,marines).
enlist(student415,foreign_legion).
enlist(student407,fire_department).
enlist(student391,air_force).
enlist(student386,foreign_legion).
enlist(student382,marines).
enlist(student380,navy).
enlist(student378,navy).
enlist(student377,peace_corps).
enlist(student369,navy).
enlist(student367,army).
enlist(student365,fire_department).
enlist(student361,army).
enlist(student353,fire_department).
enlist(student349,navy).
enlist(student348,fire_department).
enlist(student340,army).
enlist(student338,fire_department).
enlist(student337,peace_corps).
enlist(student334,marines).
enlist(student317,navy).
enlist(student316,peace_corps).
enlist(student315,foreign_legion).
enlist(student313,air_force).
enlist(student308,air_force).
enlist(student306,foreign_legion).
enlist(student304,army).
enlist(student303,fire_department).
enlist(student302,fire_department).
enlist(student297,navy).
enlist(student295,navy).
enlist(student293,navy).
enlist(student292,foreign_legion).
enlist(student291,army).
enlist(student285,marines).
enlist(student282,marines).
enlist(student281,navy).
enlist(student280,air_force).
enlist(student279,army).
enlist(student275,navy).
enlist(student272,navy).
enlist(student271,fire_department).
enlist(student264,foreign_legion).
enlist(student248,army).
enlist(student233,navy).
enlist(student224,peace_corps).
enlist(student220,peace_corps).
enlist(student218,fire_department).
enlist(student208,foreign_legion).
enlist(student204,marines).
enlist(student196,peace_corps).
enlist(student195,marines).
enlist(student192,foreign_legion).
enlist(student191,army).
enlist(student189,peace_corps).
enlist(student180,fire_department).
enlist(student172,peace_corps).
enlist(student169,navy).
enlist(student168,air_force).
enlist(student165,foreign_legion).
enlist(student161,foreign_legion).
enlist(student160,fire_department).
enlist(student153,peace_corps).
enlist(student152,army).
enlist(student151,army).
enlist(student140,air_force).
enlist(student139,fire_department).
enlist(student129,peace_corps).
enlist(student127,marines).
enlist(student121,army).
enlist(student120,army).
enlist(student117,fire_department).
enlist(student116,fire_department).
enlist(student106,army).
enlist(student105,army).
enlist(student104,marines).
enlist(student101,foreign_legion).
enlist(student99,air_force).
enlist(student97,navy).
enlist(student94,peace_corps).
enlist(student91,navy).
enlist(student90,fire_department).
enlist(student84,marines).
enlist(student80,air_force).
enlist(student79,army).
enlist(student73,air_force).
enlist(student62,army).
enlist(student57,marines).
enlist(student53,foreign_legion).
enlist(student51,marines).
enlist(student49,army).
enlist(student48,army).
enlist(student46,army).
enlist(student39,navy).
enlist(student21,marines).
enlist(student13,peace_corps).
enlist(student11,peace_corps).
enlist(student9,marines).
enlist(student4,marines).
