filed_for_bankrupcy(student999).
filed_for_bankrupcy(student998).
filed_for_bankrupcy(student958).
filed_for_bankrupcy(student956).
filed_for_bankrupcy(student953).
filed_for_bankrupcy(student932).
filed_for_bankrupcy(student928).
filed_for_bankrupcy(student924).
filed_for_bankrupcy(student915).
filed_for_bankrupcy(student891).
filed_for_bankrupcy(student890).
filed_for_bankrupcy(student874).
filed_for_bankrupcy(student854).
filed_for_bankrupcy(student849).
filed_for_bankrupcy(student847).
filed_for_bankrupcy(student835).
filed_for_bankrupcy(student817).
filed_for_bankrupcy(student814).
filed_for_bankrupcy(student807).
filed_for_bankrupcy(student803).
filed_for_bankrupcy(student792).
filed_for_bankrupcy(student787).
filed_for_bankrupcy(student780).
filed_for_bankrupcy(student764).
filed_for_bankrupcy(student760).
filed_for_bankrupcy(student749).
filed_for_bankrupcy(student747).
filed_for_bankrupcy(student742).
filed_for_bankrupcy(student686).
filed_for_bankrupcy(student663).
filed_for_bankrupcy(student661).
filed_for_bankrupcy(student651).
filed_for_bankrupcy(student641).
filed_for_bankrupcy(student606).
filed_for_bankrupcy(student592).
filed_for_bankrupcy(student591).
filed_for_bankrupcy(student588).
filed_for_bankrupcy(student585).
filed_for_bankrupcy(student570).
filed_for_bankrupcy(student553).
filed_for_bankrupcy(student526).
filed_for_bankrupcy(student522).
filed_for_bankrupcy(student512).
filed_for_bankrupcy(student511).
filed_for_bankrupcy(student505).
filed_for_bankrupcy(student502).
filed_for_bankrupcy(student495).
filed_for_bankrupcy(student490).
filed_for_bankrupcy(student477).
filed_for_bankrupcy(student467).
filed_for_bankrupcy(student448).
filed_for_bankrupcy(student438).
filed_for_bankrupcy(student436).
filed_for_bankrupcy(student433).
filed_for_bankrupcy(student416).
filed_for_bankrupcy(student409).
filed_for_bankrupcy(student406).
filed_for_bankrupcy(student396).
filed_for_bankrupcy(student385).
filed_for_bankrupcy(student377).
filed_for_bankrupcy(student376).
filed_for_bankrupcy(student350).
filed_for_bankrupcy(student347).
filed_for_bankrupcy(student323).
filed_for_bankrupcy(student302).
filed_for_bankrupcy(student300).
filed_for_bankrupcy(student280).
filed_for_bankrupcy(student270).
filed_for_bankrupcy(student262).
filed_for_bankrupcy(student253).
filed_for_bankrupcy(student248).
filed_for_bankrupcy(student247).
filed_for_bankrupcy(student244).
filed_for_bankrupcy(student242).
filed_for_bankrupcy(student241).
filed_for_bankrupcy(student238).
filed_for_bankrupcy(student227).
filed_for_bankrupcy(student219).
filed_for_bankrupcy(student211).
filed_for_bankrupcy(student179).
filed_for_bankrupcy(student170).
filed_for_bankrupcy(student162).
filed_for_bankrupcy(student159).
filed_for_bankrupcy(student148).
filed_for_bankrupcy(student145).
filed_for_bankrupcy(student136).
filed_for_bankrupcy(student126).
filed_for_bankrupcy(student122).
filed_for_bankrupcy(student97).
filed_for_bankrupcy(student95).
filed_for_bankrupcy(student84).
filed_for_bankrupcy(student66).
filed_for_bankrupcy(student59).
filed_for_bankrupcy(student33).
filed_for_bankrupcy(student7).
filed_for_bankrupcy(student2).
