% longest_absense_from_school(Person,Months).
% longest absense from school in months

longest_absense_from_school(student1000,7).
longest_absense_from_school(student999,4).
longest_absense_from_school(student998,1).
longest_absense_from_school(student997,8).
longest_absense_from_school(student996,7).
longest_absense_from_school(student995,8).
longest_absense_from_school(student994,1).
longest_absense_from_school(student993,4).
longest_absense_from_school(student992,7).
longest_absense_from_school(student991,5).
longest_absense_from_school(student990,4).
longest_absense_from_school(student989,9).
longest_absense_from_school(student988,9).
longest_absense_from_school(student987,5).
longest_absense_from_school(student986,4).
longest_absense_from_school(student985,9).
longest_absense_from_school(student984,3).
longest_absense_from_school(student983,2).
longest_absense_from_school(student982,5).
longest_absense_from_school(student981,5).
longest_absense_from_school(student980,6).
longest_absense_from_school(student979,9).
longest_absense_from_school(student978,6).
longest_absense_from_school(student977,4).
longest_absense_from_school(student976,1).
longest_absense_from_school(student975,9).
longest_absense_from_school(student974,7).
longest_absense_from_school(student973,7).
longest_absense_from_school(student972,1).
longest_absense_from_school(student971,7).
longest_absense_from_school(student970,0).
longest_absense_from_school(student969,0).
longest_absense_from_school(student968,8).
longest_absense_from_school(student967,4).
longest_absense_from_school(student966,9).
longest_absense_from_school(student965,9).
longest_absense_from_school(student964,7).
longest_absense_from_school(student963,5).
longest_absense_from_school(student962,1).
longest_absense_from_school(student961,6).
longest_absense_from_school(student960,3).
longest_absense_from_school(student959,1).
longest_absense_from_school(student958,3).
longest_absense_from_school(student957,2).
longest_absense_from_school(student956,1).
longest_absense_from_school(student955,7).
longest_absense_from_school(student954,4).
longest_absense_from_school(student953,1).
longest_absense_from_school(student952,9).
longest_absense_from_school(student951,4).
longest_absense_from_school(student950,1).
longest_absense_from_school(student949,5).
longest_absense_from_school(student948,5).
longest_absense_from_school(student947,4).
longest_absense_from_school(student946,1).
longest_absense_from_school(student945,4).
longest_absense_from_school(student944,6).
longest_absense_from_school(student943,5).
longest_absense_from_school(student942,4).
longest_absense_from_school(student941,2).
longest_absense_from_school(student940,1).
longest_absense_from_school(student939,7).
longest_absense_from_school(student938,7).
longest_absense_from_school(student937,4).
longest_absense_from_school(student936,0).
longest_absense_from_school(student935,4).
longest_absense_from_school(student934,9).
longest_absense_from_school(student933,9).
longest_absense_from_school(student932,8).
longest_absense_from_school(student931,3).
longest_absense_from_school(student930,8).
longest_absense_from_school(student929,9).
longest_absense_from_school(student928,2).
longest_absense_from_school(student927,8).
longest_absense_from_school(student926,3).
longest_absense_from_school(student925,8).
longest_absense_from_school(student924,0).
longest_absense_from_school(student923,1).
longest_absense_from_school(student922,2).
longest_absense_from_school(student921,5).
longest_absense_from_school(student920,6).
longest_absense_from_school(student919,4).
longest_absense_from_school(student918,4).
longest_absense_from_school(student917,8).
longest_absense_from_school(student916,7).
longest_absense_from_school(student915,8).
longest_absense_from_school(student914,8).
longest_absense_from_school(student913,0).
longest_absense_from_school(student912,9).
longest_absense_from_school(student911,7).
longest_absense_from_school(student910,4).
longest_absense_from_school(student909,5).
longest_absense_from_school(student908,5).
longest_absense_from_school(student907,9).
longest_absense_from_school(student906,1).
longest_absense_from_school(student905,9).
longest_absense_from_school(student904,4).
longest_absense_from_school(student903,0).
longest_absense_from_school(student902,6).
longest_absense_from_school(student901,1).
longest_absense_from_school(student900,6).
longest_absense_from_school(student899,0).
longest_absense_from_school(student898,9).
longest_absense_from_school(student897,2).
longest_absense_from_school(student896,2).
longest_absense_from_school(student895,6).
longest_absense_from_school(student894,1).
longest_absense_from_school(student893,3).
longest_absense_from_school(student892,7).
longest_absense_from_school(student891,3).
longest_absense_from_school(student890,7).
longest_absense_from_school(student889,1).
longest_absense_from_school(student888,9).
longest_absense_from_school(student887,4).
longest_absense_from_school(student886,8).
longest_absense_from_school(student885,6).
longest_absense_from_school(student884,7).
longest_absense_from_school(student883,6).
longest_absense_from_school(student882,6).
longest_absense_from_school(student881,1).
longest_absense_from_school(student880,8).
longest_absense_from_school(student879,0).
longest_absense_from_school(student878,0).
longest_absense_from_school(student877,5).
longest_absense_from_school(student876,1).
longest_absense_from_school(student875,0).
longest_absense_from_school(student874,5).
longest_absense_from_school(student873,8).
longest_absense_from_school(student872,9).
longest_absense_from_school(student871,4).
longest_absense_from_school(student870,0).
longest_absense_from_school(student869,0).
longest_absense_from_school(student868,3).
longest_absense_from_school(student867,6).
longest_absense_from_school(student866,5).
longest_absense_from_school(student865,9).
longest_absense_from_school(student864,4).
longest_absense_from_school(student863,0).
longest_absense_from_school(student862,1).
longest_absense_from_school(student861,9).
longest_absense_from_school(student860,9).
longest_absense_from_school(student859,4).
longest_absense_from_school(student858,8).
longest_absense_from_school(student857,3).
longest_absense_from_school(student856,3).
longest_absense_from_school(student855,1).
longest_absense_from_school(student854,1).
longest_absense_from_school(student853,8).
longest_absense_from_school(student852,4).
longest_absense_from_school(student851,6).
longest_absense_from_school(student850,1).
longest_absense_from_school(student849,5).
longest_absense_from_school(student848,6).
longest_absense_from_school(student847,8).
longest_absense_from_school(student846,4).
longest_absense_from_school(student845,8).
longest_absense_from_school(student844,6).
longest_absense_from_school(student843,9).
longest_absense_from_school(student842,0).
longest_absense_from_school(student841,5).
longest_absense_from_school(student840,0).
longest_absense_from_school(student839,6).
longest_absense_from_school(student838,4).
longest_absense_from_school(student837,3).
longest_absense_from_school(student836,1).
longest_absense_from_school(student835,5).
longest_absense_from_school(student834,7).
longest_absense_from_school(student833,7).
longest_absense_from_school(student832,0).
longest_absense_from_school(student831,3).
longest_absense_from_school(student830,9).
longest_absense_from_school(student829,8).
longest_absense_from_school(student828,4).
longest_absense_from_school(student827,5).
longest_absense_from_school(student826,7).
longest_absense_from_school(student825,4).
longest_absense_from_school(student824,9).
longest_absense_from_school(student823,2).
longest_absense_from_school(student822,8).
longest_absense_from_school(student821,3).
longest_absense_from_school(student820,3).
longest_absense_from_school(student819,7).
longest_absense_from_school(student818,8).
longest_absense_from_school(student817,3).
longest_absense_from_school(student816,2).
longest_absense_from_school(student815,4).
longest_absense_from_school(student814,5).
longest_absense_from_school(student813,7).
longest_absense_from_school(student812,3).
longest_absense_from_school(student811,9).
longest_absense_from_school(student810,4).
longest_absense_from_school(student809,1).
longest_absense_from_school(student808,4).
longest_absense_from_school(student807,2).
longest_absense_from_school(student806,0).
longest_absense_from_school(student805,9).
longest_absense_from_school(student804,1).
longest_absense_from_school(student803,3).
longest_absense_from_school(student802,6).
longest_absense_from_school(student801,1).
longest_absense_from_school(student800,3).
longest_absense_from_school(student799,0).
longest_absense_from_school(student798,2).
longest_absense_from_school(student797,4).
longest_absense_from_school(student796,6).
longest_absense_from_school(student795,2).
longest_absense_from_school(student794,1).
longest_absense_from_school(student793,3).
longest_absense_from_school(student792,0).
longest_absense_from_school(student791,8).
longest_absense_from_school(student790,1).
longest_absense_from_school(student789,2).
longest_absense_from_school(student788,4).
longest_absense_from_school(student787,1).
longest_absense_from_school(student786,8).
longest_absense_from_school(student785,4).
longest_absense_from_school(student784,1).
longest_absense_from_school(student783,0).
longest_absense_from_school(student782,7).
longest_absense_from_school(student781,9).
longest_absense_from_school(student780,2).
longest_absense_from_school(student779,8).
longest_absense_from_school(student778,8).
longest_absense_from_school(student777,2).
longest_absense_from_school(student776,3).
longest_absense_from_school(student775,3).
longest_absense_from_school(student774,2).
longest_absense_from_school(student773,3).
longest_absense_from_school(student772,7).
longest_absense_from_school(student771,4).
longest_absense_from_school(student770,4).
longest_absense_from_school(student769,1).
longest_absense_from_school(student768,5).
longest_absense_from_school(student767,3).
longest_absense_from_school(student766,4).
longest_absense_from_school(student765,9).
longest_absense_from_school(student764,2).
longest_absense_from_school(student763,4).
longest_absense_from_school(student762,7).
longest_absense_from_school(student761,5).
longest_absense_from_school(student760,9).
longest_absense_from_school(student759,6).
longest_absense_from_school(student758,3).
longest_absense_from_school(student757,5).
longest_absense_from_school(student756,2).
longest_absense_from_school(student755,6).
longest_absense_from_school(student754,0).
longest_absense_from_school(student753,1).
longest_absense_from_school(student752,8).
longest_absense_from_school(student751,2).
longest_absense_from_school(student750,4).
longest_absense_from_school(student749,4).
longest_absense_from_school(student748,5).
longest_absense_from_school(student747,7).
longest_absense_from_school(student746,5).
longest_absense_from_school(student745,2).
longest_absense_from_school(student744,5).
longest_absense_from_school(student743,0).
longest_absense_from_school(student742,3).
longest_absense_from_school(student741,2).
longest_absense_from_school(student740,1).
longest_absense_from_school(student739,0).
longest_absense_from_school(student738,6).
longest_absense_from_school(student737,8).
longest_absense_from_school(student736,6).
longest_absense_from_school(student735,3).
longest_absense_from_school(student734,0).
longest_absense_from_school(student733,4).
longest_absense_from_school(student732,1).
longest_absense_from_school(student731,8).
longest_absense_from_school(student730,8).
longest_absense_from_school(student729,1).
longest_absense_from_school(student728,3).
longest_absense_from_school(student727,2).
longest_absense_from_school(student726,5).
longest_absense_from_school(student725,2).
longest_absense_from_school(student724,3).
longest_absense_from_school(student723,8).
longest_absense_from_school(student722,6).
longest_absense_from_school(student721,1).
longest_absense_from_school(student720,3).
longest_absense_from_school(student719,5).
longest_absense_from_school(student718,9).
longest_absense_from_school(student717,6).
longest_absense_from_school(student716,9).
longest_absense_from_school(student715,2).
longest_absense_from_school(student714,0).
longest_absense_from_school(student713,8).
longest_absense_from_school(student712,4).
longest_absense_from_school(student711,6).
longest_absense_from_school(student710,1).
longest_absense_from_school(student709,9).
longest_absense_from_school(student708,8).
longest_absense_from_school(student707,6).
longest_absense_from_school(student706,6).
longest_absense_from_school(student705,0).
longest_absense_from_school(student704,3).
longest_absense_from_school(student703,9).
longest_absense_from_school(student702,5).
longest_absense_from_school(student701,9).
longest_absense_from_school(student700,3).
longest_absense_from_school(student699,8).
longest_absense_from_school(student698,7).
longest_absense_from_school(student697,2).
longest_absense_from_school(student696,2).
longest_absense_from_school(student695,1).
longest_absense_from_school(student694,4).
longest_absense_from_school(student693,1).
longest_absense_from_school(student692,6).
longest_absense_from_school(student691,7).
longest_absense_from_school(student690,6).
longest_absense_from_school(student689,0).
longest_absense_from_school(student688,2).
longest_absense_from_school(student687,2).
longest_absense_from_school(student686,1).
longest_absense_from_school(student685,7).
longest_absense_from_school(student684,1).
longest_absense_from_school(student683,6).
longest_absense_from_school(student682,1).
longest_absense_from_school(student681,8).
longest_absense_from_school(student680,7).
longest_absense_from_school(student679,8).
longest_absense_from_school(student678,0).
longest_absense_from_school(student677,2).
longest_absense_from_school(student676,9).
longest_absense_from_school(student675,4).
longest_absense_from_school(student674,5).
longest_absense_from_school(student673,4).
longest_absense_from_school(student672,5).
longest_absense_from_school(student671,4).
longest_absense_from_school(student670,3).
longest_absense_from_school(student669,6).
longest_absense_from_school(student668,5).
longest_absense_from_school(student667,0).
longest_absense_from_school(student666,1).
longest_absense_from_school(student665,3).
longest_absense_from_school(student664,8).
longest_absense_from_school(student663,4).
longest_absense_from_school(student662,1).
longest_absense_from_school(student661,1).
longest_absense_from_school(student660,8).
longest_absense_from_school(student659,5).
longest_absense_from_school(student658,3).
longest_absense_from_school(student657,4).
longest_absense_from_school(student656,5).
longest_absense_from_school(student655,2).
longest_absense_from_school(student654,9).
longest_absense_from_school(student653,9).
longest_absense_from_school(student652,1).
longest_absense_from_school(student651,7).
longest_absense_from_school(student650,5).
longest_absense_from_school(student649,5).
longest_absense_from_school(student648,3).
longest_absense_from_school(student647,5).
longest_absense_from_school(student646,5).
longest_absense_from_school(student645,9).
longest_absense_from_school(student644,5).
longest_absense_from_school(student643,9).
longest_absense_from_school(student642,1).
longest_absense_from_school(student641,3).
longest_absense_from_school(student640,7).
longest_absense_from_school(student639,6).
longest_absense_from_school(student638,5).
longest_absense_from_school(student637,4).
longest_absense_from_school(student636,2).
longest_absense_from_school(student635,3).
longest_absense_from_school(student634,5).
longest_absense_from_school(student633,0).
longest_absense_from_school(student632,4).
longest_absense_from_school(student631,4).
longest_absense_from_school(student630,5).
longest_absense_from_school(student629,5).
longest_absense_from_school(student628,7).
longest_absense_from_school(student627,2).
longest_absense_from_school(student626,4).
longest_absense_from_school(student625,4).
longest_absense_from_school(student624,4).
longest_absense_from_school(student623,4).
longest_absense_from_school(student622,0).
longest_absense_from_school(student621,3).
longest_absense_from_school(student620,3).
longest_absense_from_school(student619,4).
longest_absense_from_school(student618,2).
longest_absense_from_school(student617,3).
longest_absense_from_school(student616,7).
longest_absense_from_school(student615,5).
longest_absense_from_school(student614,0).
longest_absense_from_school(student613,2).
longest_absense_from_school(student612,4).
longest_absense_from_school(student611,4).
longest_absense_from_school(student610,3).
longest_absense_from_school(student609,0).
longest_absense_from_school(student608,3).
longest_absense_from_school(student607,3).
longest_absense_from_school(student606,1).
longest_absense_from_school(student605,9).
longest_absense_from_school(student604,1).
longest_absense_from_school(student603,6).
longest_absense_from_school(student602,0).
longest_absense_from_school(student601,1).
longest_absense_from_school(student600,2).
longest_absense_from_school(student599,4).
longest_absense_from_school(student598,2).
longest_absense_from_school(student597,7).
longest_absense_from_school(student596,5).
longest_absense_from_school(student595,5).
longest_absense_from_school(student594,1).
longest_absense_from_school(student593,6).
longest_absense_from_school(student592,4).
longest_absense_from_school(student591,6).
longest_absense_from_school(student590,4).
longest_absense_from_school(student589,4).
longest_absense_from_school(student588,3).
longest_absense_from_school(student587,8).
longest_absense_from_school(student586,3).
longest_absense_from_school(student585,6).
longest_absense_from_school(student584,2).
longest_absense_from_school(student583,2).
longest_absense_from_school(student582,9).
longest_absense_from_school(student581,3).
longest_absense_from_school(student580,6).
longest_absense_from_school(student579,9).
longest_absense_from_school(student578,2).
longest_absense_from_school(student577,7).
longest_absense_from_school(student576,5).
longest_absense_from_school(student575,5).
longest_absense_from_school(student574,6).
longest_absense_from_school(student573,2).
longest_absense_from_school(student572,3).
longest_absense_from_school(student571,9).
longest_absense_from_school(student570,8).
longest_absense_from_school(student569,8).
longest_absense_from_school(student568,4).
longest_absense_from_school(student567,0).
longest_absense_from_school(student566,7).
longest_absense_from_school(student565,9).
longest_absense_from_school(student564,1).
longest_absense_from_school(student563,6).
longest_absense_from_school(student562,5).
longest_absense_from_school(student561,7).
longest_absense_from_school(student560,1).
longest_absense_from_school(student559,7).
longest_absense_from_school(student558,1).
longest_absense_from_school(student557,5).
longest_absense_from_school(student556,4).
longest_absense_from_school(student555,6).
longest_absense_from_school(student554,1).
longest_absense_from_school(student553,4).
longest_absense_from_school(student552,8).
longest_absense_from_school(student551,7).
longest_absense_from_school(student550,2).
longest_absense_from_school(student549,8).
longest_absense_from_school(student548,6).
longest_absense_from_school(student547,5).
longest_absense_from_school(student546,6).
longest_absense_from_school(student545,7).
longest_absense_from_school(student544,9).
longest_absense_from_school(student543,8).
longest_absense_from_school(student542,7).
longest_absense_from_school(student541,0).
longest_absense_from_school(student540,9).
longest_absense_from_school(student539,8).
longest_absense_from_school(student538,4).
longest_absense_from_school(student537,9).
longest_absense_from_school(student536,8).
longest_absense_from_school(student535,5).
longest_absense_from_school(student534,3).
longest_absense_from_school(student533,0).
longest_absense_from_school(student532,9).
longest_absense_from_school(student531,1).
longest_absense_from_school(student530,6).
longest_absense_from_school(student529,3).
longest_absense_from_school(student528,8).
longest_absense_from_school(student527,0).
longest_absense_from_school(student526,3).
longest_absense_from_school(student525,6).
longest_absense_from_school(student524,0).
longest_absense_from_school(student523,8).
longest_absense_from_school(student522,9).
longest_absense_from_school(student521,2).
longest_absense_from_school(student520,9).
longest_absense_from_school(student519,8).
longest_absense_from_school(student518,8).
longest_absense_from_school(student517,7).
longest_absense_from_school(student516,9).
longest_absense_from_school(student515,4).
longest_absense_from_school(student514,7).
longest_absense_from_school(student513,3).
longest_absense_from_school(student512,8).
longest_absense_from_school(student511,1).
longest_absense_from_school(student510,6).
longest_absense_from_school(student509,7).
longest_absense_from_school(student508,4).
longest_absense_from_school(student507,7).
longest_absense_from_school(student506,4).
longest_absense_from_school(student505,5).
longest_absense_from_school(student504,9).
longest_absense_from_school(student503,3).
longest_absense_from_school(student502,2).
longest_absense_from_school(student501,6).
longest_absense_from_school(student500,0).
longest_absense_from_school(student499,8).
longest_absense_from_school(student498,0).
longest_absense_from_school(student497,5).
longest_absense_from_school(student496,2).
longest_absense_from_school(student495,3).
longest_absense_from_school(student494,7).
longest_absense_from_school(student493,5).
longest_absense_from_school(student492,3).
longest_absense_from_school(student491,5).
longest_absense_from_school(student490,3).
longest_absense_from_school(student489,5).
longest_absense_from_school(student488,8).
longest_absense_from_school(student487,9).
longest_absense_from_school(student486,0).
longest_absense_from_school(student485,0).
longest_absense_from_school(student484,8).
longest_absense_from_school(student483,6).
longest_absense_from_school(student482,8).
longest_absense_from_school(student481,5).
longest_absense_from_school(student480,4).
longest_absense_from_school(student479,0).
longest_absense_from_school(student478,3).
longest_absense_from_school(student477,0).
longest_absense_from_school(student476,0).
longest_absense_from_school(student475,3).
longest_absense_from_school(student474,4).
longest_absense_from_school(student473,5).
longest_absense_from_school(student472,3).
longest_absense_from_school(student471,0).
longest_absense_from_school(student470,2).
longest_absense_from_school(student469,6).
longest_absense_from_school(student468,8).
longest_absense_from_school(student467,0).
longest_absense_from_school(student466,2).
longest_absense_from_school(student465,0).
longest_absense_from_school(student464,5).
longest_absense_from_school(student463,0).
longest_absense_from_school(student462,1).
longest_absense_from_school(student461,5).
longest_absense_from_school(student460,3).
longest_absense_from_school(student459,2).
longest_absense_from_school(student458,8).
longest_absense_from_school(student457,8).
longest_absense_from_school(student456,3).
longest_absense_from_school(student455,5).
longest_absense_from_school(student454,8).
longest_absense_from_school(student453,6).
longest_absense_from_school(student452,9).
longest_absense_from_school(student451,7).
longest_absense_from_school(student450,4).
longest_absense_from_school(student449,7).
longest_absense_from_school(student448,5).
longest_absense_from_school(student447,2).
longest_absense_from_school(student446,3).
longest_absense_from_school(student445,9).
longest_absense_from_school(student444,3).
longest_absense_from_school(student443,7).
longest_absense_from_school(student442,9).
longest_absense_from_school(student441,6).
longest_absense_from_school(student440,2).
longest_absense_from_school(student439,0).
longest_absense_from_school(student438,5).
longest_absense_from_school(student437,0).
longest_absense_from_school(student436,2).
longest_absense_from_school(student435,9).
longest_absense_from_school(student434,8).
longest_absense_from_school(student433,6).
longest_absense_from_school(student432,4).
longest_absense_from_school(student431,3).
longest_absense_from_school(student430,0).
longest_absense_from_school(student429,4).
longest_absense_from_school(student428,2).
longest_absense_from_school(student427,5).
longest_absense_from_school(student426,6).
longest_absense_from_school(student425,1).
longest_absense_from_school(student424,6).
longest_absense_from_school(student423,3).
longest_absense_from_school(student422,6).
longest_absense_from_school(student421,5).
longest_absense_from_school(student420,8).
longest_absense_from_school(student419,6).
longest_absense_from_school(student418,1).
longest_absense_from_school(student417,3).
longest_absense_from_school(student416,8).
longest_absense_from_school(student415,7).
longest_absense_from_school(student414,1).
longest_absense_from_school(student413,3).
longest_absense_from_school(student412,2).
longest_absense_from_school(student411,7).
longest_absense_from_school(student410,2).
longest_absense_from_school(student409,7).
longest_absense_from_school(student408,8).
longest_absense_from_school(student407,4).
longest_absense_from_school(student406,0).
longest_absense_from_school(student405,0).
longest_absense_from_school(student404,3).
longest_absense_from_school(student403,2).
longest_absense_from_school(student402,7).
longest_absense_from_school(student401,7).
longest_absense_from_school(student400,5).
longest_absense_from_school(student399,0).
longest_absense_from_school(student398,8).
longest_absense_from_school(student397,2).
longest_absense_from_school(student396,4).
longest_absense_from_school(student395,0).
longest_absense_from_school(student394,1).
longest_absense_from_school(student393,7).
longest_absense_from_school(student392,8).
longest_absense_from_school(student391,1).
longest_absense_from_school(student390,5).
longest_absense_from_school(student389,1).
longest_absense_from_school(student388,4).
longest_absense_from_school(student387,3).
longest_absense_from_school(student386,0).
longest_absense_from_school(student385,9).
longest_absense_from_school(student384,6).
longest_absense_from_school(student383,2).
longest_absense_from_school(student382,5).
longest_absense_from_school(student381,8).
longest_absense_from_school(student380,6).
longest_absense_from_school(student379,7).
longest_absense_from_school(student378,2).
longest_absense_from_school(student377,9).
longest_absense_from_school(student376,7).
longest_absense_from_school(student375,7).
longest_absense_from_school(student374,7).
longest_absense_from_school(student373,3).
longest_absense_from_school(student372,2).
longest_absense_from_school(student371,8).
longest_absense_from_school(student370,5).
longest_absense_from_school(student369,8).
longest_absense_from_school(student368,4).
longest_absense_from_school(student367,0).
longest_absense_from_school(student366,6).
longest_absense_from_school(student365,0).
longest_absense_from_school(student364,4).
longest_absense_from_school(student363,7).
longest_absense_from_school(student362,2).
longest_absense_from_school(student361,2).
longest_absense_from_school(student360,8).
longest_absense_from_school(student359,3).
longest_absense_from_school(student358,4).
longest_absense_from_school(student357,9).
longest_absense_from_school(student356,5).
longest_absense_from_school(student355,4).
longest_absense_from_school(student354,3).
longest_absense_from_school(student353,5).
longest_absense_from_school(student352,9).
longest_absense_from_school(student351,9).
longest_absense_from_school(student350,3).
longest_absense_from_school(student349,0).
longest_absense_from_school(student348,9).
longest_absense_from_school(student347,2).
longest_absense_from_school(student346,3).
longest_absense_from_school(student345,7).
longest_absense_from_school(student344,7).
longest_absense_from_school(student343,6).
longest_absense_from_school(student342,6).
longest_absense_from_school(student341,9).
longest_absense_from_school(student340,6).
longest_absense_from_school(student339,3).
longest_absense_from_school(student338,5).
longest_absense_from_school(student337,1).
longest_absense_from_school(student336,4).
longest_absense_from_school(student335,4).
longest_absense_from_school(student334,4).
longest_absense_from_school(student333,0).
longest_absense_from_school(student332,2).
longest_absense_from_school(student331,0).
longest_absense_from_school(student330,3).
longest_absense_from_school(student329,2).
longest_absense_from_school(student328,6).
longest_absense_from_school(student327,5).
longest_absense_from_school(student326,8).
longest_absense_from_school(student325,7).
longest_absense_from_school(student324,5).
longest_absense_from_school(student323,4).
longest_absense_from_school(student322,4).
longest_absense_from_school(student321,0).
longest_absense_from_school(student320,7).
longest_absense_from_school(student319,8).
longest_absense_from_school(student318,9).
longest_absense_from_school(student317,4).
longest_absense_from_school(student316,4).
longest_absense_from_school(student315,5).
longest_absense_from_school(student314,5).
longest_absense_from_school(student313,4).
longest_absense_from_school(student312,1).
longest_absense_from_school(student311,6).
longest_absense_from_school(student310,0).
longest_absense_from_school(student309,2).
longest_absense_from_school(student308,2).
longest_absense_from_school(student307,7).
longest_absense_from_school(student306,2).
longest_absense_from_school(student305,5).
longest_absense_from_school(student304,3).
longest_absense_from_school(student303,8).
longest_absense_from_school(student302,3).
longest_absense_from_school(student301,7).
longest_absense_from_school(student300,0).
longest_absense_from_school(student299,6).
longest_absense_from_school(student298,6).
longest_absense_from_school(student297,7).
longest_absense_from_school(student296,2).
longest_absense_from_school(student295,2).
longest_absense_from_school(student294,1).
longest_absense_from_school(student293,6).
longest_absense_from_school(student292,9).
longest_absense_from_school(student291,7).
longest_absense_from_school(student290,7).
longest_absense_from_school(student289,9).
longest_absense_from_school(student288,6).
longest_absense_from_school(student287,8).
longest_absense_from_school(student286,5).
longest_absense_from_school(student285,5).
longest_absense_from_school(student284,5).
longest_absense_from_school(student283,3).
longest_absense_from_school(student282,2).
longest_absense_from_school(student281,2).
longest_absense_from_school(student280,0).
longest_absense_from_school(student279,7).
longest_absense_from_school(student278,4).
longest_absense_from_school(student277,0).
longest_absense_from_school(student276,3).
longest_absense_from_school(student275,8).
longest_absense_from_school(student274,3).
longest_absense_from_school(student273,5).
longest_absense_from_school(student272,6).
longest_absense_from_school(student271,9).
longest_absense_from_school(student270,2).
longest_absense_from_school(student269,9).
longest_absense_from_school(student268,9).
longest_absense_from_school(student267,3).
longest_absense_from_school(student266,3).
longest_absense_from_school(student265,2).
longest_absense_from_school(student264,8).
longest_absense_from_school(student263,5).
longest_absense_from_school(student262,4).
longest_absense_from_school(student261,1).
longest_absense_from_school(student260,4).
longest_absense_from_school(student259,9).
longest_absense_from_school(student258,2).
longest_absense_from_school(student257,1).
longest_absense_from_school(student256,0).
longest_absense_from_school(student255,2).
longest_absense_from_school(student254,8).
longest_absense_from_school(student253,7).
longest_absense_from_school(student252,3).
longest_absense_from_school(student251,1).
longest_absense_from_school(student250,2).
longest_absense_from_school(student249,8).
longest_absense_from_school(student248,0).
longest_absense_from_school(student247,1).
longest_absense_from_school(student246,5).
longest_absense_from_school(student245,3).
longest_absense_from_school(student244,7).
longest_absense_from_school(student243,6).
longest_absense_from_school(student242,7).
longest_absense_from_school(student241,2).
longest_absense_from_school(student240,8).
longest_absense_from_school(student239,7).
longest_absense_from_school(student238,7).
longest_absense_from_school(student237,2).
longest_absense_from_school(student236,6).
longest_absense_from_school(student235,1).
longest_absense_from_school(student234,8).
longest_absense_from_school(student233,4).
longest_absense_from_school(student232,4).
longest_absense_from_school(student231,5).
longest_absense_from_school(student230,8).
longest_absense_from_school(student229,1).
longest_absense_from_school(student228,6).
longest_absense_from_school(student227,0).
longest_absense_from_school(student226,0).
longest_absense_from_school(student225,4).
longest_absense_from_school(student224,1).
longest_absense_from_school(student223,6).
longest_absense_from_school(student222,2).
longest_absense_from_school(student221,3).
longest_absense_from_school(student220,5).
longest_absense_from_school(student219,6).
longest_absense_from_school(student218,4).
longest_absense_from_school(student217,4).
longest_absense_from_school(student216,2).
longest_absense_from_school(student215,7).
longest_absense_from_school(student214,0).
longest_absense_from_school(student213,4).
longest_absense_from_school(student212,5).
longest_absense_from_school(student211,5).
longest_absense_from_school(student210,3).
longest_absense_from_school(student209,0).
longest_absense_from_school(student208,6).
longest_absense_from_school(student207,1).
longest_absense_from_school(student206,0).
longest_absense_from_school(student205,0).
longest_absense_from_school(student204,4).
longest_absense_from_school(student203,2).
longest_absense_from_school(student202,0).
longest_absense_from_school(student201,1).
longest_absense_from_school(student200,8).
longest_absense_from_school(student199,2).
longest_absense_from_school(student198,5).
longest_absense_from_school(student197,7).
longest_absense_from_school(student196,5).
longest_absense_from_school(student195,3).
longest_absense_from_school(student194,6).
longest_absense_from_school(student193,7).
longest_absense_from_school(student192,1).
longest_absense_from_school(student191,7).
longest_absense_from_school(student190,7).
longest_absense_from_school(student189,4).
longest_absense_from_school(student188,7).
longest_absense_from_school(student187,3).
longest_absense_from_school(student186,9).
longest_absense_from_school(student185,9).
longest_absense_from_school(student184,6).
longest_absense_from_school(student183,2).
longest_absense_from_school(student182,7).
longest_absense_from_school(student181,7).
longest_absense_from_school(student180,5).
longest_absense_from_school(student179,9).
longest_absense_from_school(student178,4).
longest_absense_from_school(student177,7).
longest_absense_from_school(student176,7).
longest_absense_from_school(student175,4).
longest_absense_from_school(student174,6).
longest_absense_from_school(student173,1).
longest_absense_from_school(student172,6).
longest_absense_from_school(student171,5).
longest_absense_from_school(student170,0).
longest_absense_from_school(student169,0).
longest_absense_from_school(student168,6).
longest_absense_from_school(student167,1).
longest_absense_from_school(student166,1).
longest_absense_from_school(student165,1).
longest_absense_from_school(student164,6).
longest_absense_from_school(student163,7).
longest_absense_from_school(student162,6).
longest_absense_from_school(student161,6).
longest_absense_from_school(student160,4).
longest_absense_from_school(student159,9).
longest_absense_from_school(student158,6).
longest_absense_from_school(student157,2).
longest_absense_from_school(student156,9).
longest_absense_from_school(student155,4).
longest_absense_from_school(student154,0).
longest_absense_from_school(student153,4).
longest_absense_from_school(student152,8).
longest_absense_from_school(student151,4).
longest_absense_from_school(student150,5).
longest_absense_from_school(student149,9).
longest_absense_from_school(student148,1).
longest_absense_from_school(student147,8).
longest_absense_from_school(student146,6).
longest_absense_from_school(student145,5).
longest_absense_from_school(student144,9).
longest_absense_from_school(student143,4).
longest_absense_from_school(student142,4).
longest_absense_from_school(student141,8).
longest_absense_from_school(student140,2).
longest_absense_from_school(student139,0).
longest_absense_from_school(student138,2).
longest_absense_from_school(student137,0).
longest_absense_from_school(student136,7).
longest_absense_from_school(student135,3).
longest_absense_from_school(student134,1).
longest_absense_from_school(student133,2).
longest_absense_from_school(student132,4).
longest_absense_from_school(student131,7).
longest_absense_from_school(student130,3).
longest_absense_from_school(student129,9).
longest_absense_from_school(student128,8).
longest_absense_from_school(student127,9).
longest_absense_from_school(student126,9).
longest_absense_from_school(student125,3).
longest_absense_from_school(student124,0).
longest_absense_from_school(student123,4).
longest_absense_from_school(student122,3).
longest_absense_from_school(student121,1).
longest_absense_from_school(student120,2).
longest_absense_from_school(student119,0).
longest_absense_from_school(student118,0).
longest_absense_from_school(student117,1).
longest_absense_from_school(student116,7).
longest_absense_from_school(student115,7).
longest_absense_from_school(student114,0).
longest_absense_from_school(student113,5).
longest_absense_from_school(student112,4).
longest_absense_from_school(student111,0).
longest_absense_from_school(student110,0).
longest_absense_from_school(student109,1).
longest_absense_from_school(student108,3).
longest_absense_from_school(student107,6).
longest_absense_from_school(student106,1).
longest_absense_from_school(student105,5).
longest_absense_from_school(student104,6).
longest_absense_from_school(student103,6).
longest_absense_from_school(student102,0).
longest_absense_from_school(student101,8).
longest_absense_from_school(student100,1).
longest_absense_from_school(student99,8).
longest_absense_from_school(student98,6).
longest_absense_from_school(student97,8).
longest_absense_from_school(student96,0).
longest_absense_from_school(student95,9).
longest_absense_from_school(student94,5).
longest_absense_from_school(student93,2).
longest_absense_from_school(student92,3).
longest_absense_from_school(student91,3).
longest_absense_from_school(student90,2).
longest_absense_from_school(student89,5).
longest_absense_from_school(student88,9).
longest_absense_from_school(student87,5).
longest_absense_from_school(student86,6).
longest_absense_from_school(student85,7).
longest_absense_from_school(student84,9).
longest_absense_from_school(student83,6).
longest_absense_from_school(student82,4).
longest_absense_from_school(student81,3).
longest_absense_from_school(student80,4).
longest_absense_from_school(student79,7).
longest_absense_from_school(student78,8).
longest_absense_from_school(student77,1).
longest_absense_from_school(student76,8).
longest_absense_from_school(student75,1).
longest_absense_from_school(student74,8).
longest_absense_from_school(student73,0).
longest_absense_from_school(student72,9).
longest_absense_from_school(student71,7).
longest_absense_from_school(student70,5).
longest_absense_from_school(student69,5).
longest_absense_from_school(student68,0).
longest_absense_from_school(student67,5).
longest_absense_from_school(student66,2).
longest_absense_from_school(student65,0).
longest_absense_from_school(student64,4).
longest_absense_from_school(student63,2).
longest_absense_from_school(student62,3).
longest_absense_from_school(student61,9).
longest_absense_from_school(student60,6).
longest_absense_from_school(student59,0).
longest_absense_from_school(student58,6).
longest_absense_from_school(student57,5).
longest_absense_from_school(student56,3).
longest_absense_from_school(student55,7).
longest_absense_from_school(student54,0).
longest_absense_from_school(student53,2).
longest_absense_from_school(student52,7).
longest_absense_from_school(student51,6).
longest_absense_from_school(student50,0).
longest_absense_from_school(student49,2).
longest_absense_from_school(student48,3).
longest_absense_from_school(student47,5).
longest_absense_from_school(student46,1).
longest_absense_from_school(student45,4).
longest_absense_from_school(student44,9).
longest_absense_from_school(student43,3).
longest_absense_from_school(student42,8).
longest_absense_from_school(student41,7).
longest_absense_from_school(student40,1).
longest_absense_from_school(student39,9).
longest_absense_from_school(student38,8).
longest_absense_from_school(student37,7).
longest_absense_from_school(student36,7).
longest_absense_from_school(student35,3).
longest_absense_from_school(student34,8).
longest_absense_from_school(student33,8).
longest_absense_from_school(student32,0).
longest_absense_from_school(student31,3).
longest_absense_from_school(student30,2).
longest_absense_from_school(student29,2).
longest_absense_from_school(student28,4).
longest_absense_from_school(student27,9).
longest_absense_from_school(student26,3).
longest_absense_from_school(student25,7).
longest_absense_from_school(student24,5).
longest_absense_from_school(student23,4).
longest_absense_from_school(student22,5).
longest_absense_from_school(student21,0).
longest_absense_from_school(student20,5).
longest_absense_from_school(student19,4).
longest_absense_from_school(student18,7).
longest_absense_from_school(student17,4).
longest_absense_from_school(student16,4).
longest_absense_from_school(student15,5).
longest_absense_from_school(student14,6).
longest_absense_from_school(student13,4).
longest_absense_from_school(student12,3).
longest_absense_from_school(student11,9).
longest_absense_from_school(student10,0).
longest_absense_from_school(student9,9).
longest_absense_from_school(student8,0).
longest_absense_from_school(student7,5).
longest_absense_from_school(student6,5).
longest_absense_from_school(student5,2).
longest_absense_from_school(student4,5).
longest_absense_from_school(student3,4).
longest_absense_from_school(student2,6).
longest_absense_from_school(student1,1).
