no_payment_due(student1000,pos).
no_payment_due(student999,pos).
no_payment_due(student998,pos).
no_payment_due(student996,pos).
no_payment_due(student994,pos).
no_payment_due(student993,pos).
no_payment_due(student992,pos).
no_payment_due(student990,pos).
no_payment_due(student989,pos).
no_payment_due(student987,pos).
no_payment_due(student985,pos).
no_payment_due(student984,pos).
no_payment_due(student983,pos).
no_payment_due(student981,pos).
no_payment_due(student977,pos).
no_payment_due(student976,pos).
no_payment_due(student975,pos).
no_payment_due(student972,pos).
no_payment_due(student970,pos).
no_payment_due(student969,pos).
no_payment_due(student968,pos).
no_payment_due(student967,pos).
no_payment_due(student963,pos).
no_payment_due(student962,pos).
no_payment_due(student959,pos).
no_payment_due(student958,pos).
no_payment_due(student956,pos).
no_payment_due(student955,pos).
no_payment_due(student953,pos).
no_payment_due(student952,pos).
no_payment_due(student950,pos).
no_payment_due(student949,pos).
no_payment_due(student948,pos).
no_payment_due(student947,pos).
no_payment_due(student946,pos).
no_payment_due(student945,pos).
no_payment_due(student943,pos).
no_payment_due(student942,pos).
no_payment_due(student940,pos).
no_payment_due(student937,pos).
no_payment_due(student936,pos).
no_payment_due(student935,pos).
no_payment_due(student932,pos).
no_payment_due(student928,pos).
no_payment_due(student927,pos).
no_payment_due(student926,pos).
no_payment_due(student924,pos).
no_payment_due(student923,pos).
no_payment_due(student920,pos).
no_payment_due(student918,pos).
no_payment_due(student916,pos).
no_payment_due(student915,pos).
no_payment_due(student913,pos).
no_payment_due(student910,pos).
no_payment_due(student909,pos).
no_payment_due(student908,pos).
no_payment_due(student906,pos).
no_payment_due(student905,pos).
no_payment_due(student904,pos).
no_payment_due(student902,pos).
no_payment_due(student901,pos).
no_payment_due(student897,pos).
no_payment_due(student896,pos).
no_payment_due(student895,pos).
no_payment_due(student894,pos).
no_payment_due(student893,pos).
no_payment_due(student891,pos).
no_payment_due(student890,pos).
no_payment_due(student888,pos).
no_payment_due(student887,pos).
no_payment_due(student885,pos).
no_payment_due(student881,pos).
no_payment_due(student879,pos).
no_payment_due(student877,pos).
no_payment_due(student874,pos).
no_payment_due(student871,pos).
no_payment_due(student870,pos).
no_payment_due(student868,pos).
no_payment_due(student867,pos).
no_payment_due(student866,pos).
no_payment_due(student864,pos).
no_payment_due(student863,pos).
no_payment_due(student859,pos).
no_payment_due(student858,pos).
no_payment_due(student856,pos).
no_payment_due(student855,pos).
no_payment_due(student854,pos).
no_payment_due(student852,pos).
no_payment_due(student850,pos).
no_payment_due(student849,pos).
no_payment_due(student847,pos).
no_payment_due(student846,pos).
no_payment_due(student842,pos).
no_payment_due(student841,pos).
no_payment_due(student840,pos).
no_payment_due(student838,pos).
no_payment_due(student836,pos).
no_payment_due(student835,pos).
no_payment_due(student832,pos).
no_payment_due(student831,pos).
no_payment_due(student830,pos).
no_payment_due(student828,pos).
no_payment_due(student827,pos).
no_payment_due(student825,pos).
no_payment_due(student823,pos).
no_payment_due(student821,pos).
no_payment_due(student820,pos).
no_payment_due(student817,pos).
no_payment_due(student814,pos).
no_payment_due(student812,pos).
no_payment_due(student809,pos).
no_payment_due(student808,pos).
no_payment_due(student807,pos).
no_payment_due(student806,pos).
no_payment_due(student805,pos).
no_payment_due(student804,pos).
no_payment_due(student803,pos).
no_payment_due(student800,pos).
no_payment_due(student798,pos).
no_payment_due(student797,pos).
no_payment_due(student795,pos).
no_payment_due(student794,pos).
no_payment_due(student792,pos).
no_payment_due(student790,pos).
no_payment_due(student789,pos).
no_payment_due(student788,pos).
no_payment_due(student787,pos).
no_payment_due(student785,pos).
no_payment_due(student783,pos).
no_payment_due(student781,pos).
no_payment_due(student780,pos).
no_payment_due(student779,pos).
no_payment_due(student778,pos).
no_payment_due(student776,pos).
no_payment_due(student775,pos).
no_payment_due(student774,pos).
no_payment_due(student773,pos).
no_payment_due(student770,pos).
no_payment_due(student769,pos).
no_payment_due(student768,pos).
no_payment_due(student765,pos).
no_payment_due(student764,pos).
no_payment_due(student762,pos).
no_payment_due(student761,pos).
no_payment_due(student760,pos).
no_payment_due(student758,pos).
no_payment_due(student757,pos).
no_payment_due(student754,pos).
no_payment_due(student753,pos).
no_payment_due(student751,pos).
no_payment_due(student750,pos).
no_payment_due(student749,pos).
no_payment_due(student748,pos).
no_payment_due(student747,pos).
no_payment_due(student746,pos).
no_payment_due(student745,pos).
no_payment_due(student744,pos).
no_payment_due(student743,pos).
no_payment_due(student742,pos).
no_payment_due(student741,pos).
no_payment_due(student740,pos).
no_payment_due(student739,pos).
no_payment_due(student738,pos).
no_payment_due(student735,pos).
no_payment_due(student734,pos).
no_payment_due(student733,pos).
no_payment_due(student732,pos).
no_payment_due(student729,pos).
no_payment_due(student727,pos).
no_payment_due(student724,pos).
no_payment_due(student723,pos).
no_payment_due(student721,pos).
no_payment_due(student719,pos).
no_payment_due(student717,pos).
no_payment_due(student714,pos).
no_payment_due(student712,pos).
no_payment_due(student710,pos).
no_payment_due(student709,pos).
no_payment_due(student705,pos).
no_payment_due(student702,pos).
no_payment_due(student701,pos).
no_payment_due(student700,pos).
no_payment_due(student699,pos).
no_payment_due(student698,pos).
no_payment_due(student697,pos).
no_payment_due(student696,pos).
no_payment_due(student690,pos).
no_payment_due(student689,pos).
no_payment_due(student688,pos).
no_payment_due(student686,pos).
no_payment_due(student684,pos).
no_payment_due(student682,pos).
no_payment_due(student680,pos).
no_payment_due(student679,pos).
no_payment_due(student678,pos).
no_payment_due(student677,pos).
no_payment_due(student676,pos).
no_payment_due(student674,pos).
no_payment_due(student673,pos).
no_payment_due(student672,pos).
no_payment_due(student670,pos).
no_payment_due(student668,pos).
no_payment_due(student667,pos).
no_payment_due(student666,pos).
no_payment_due(student665,pos).
no_payment_due(student664,pos).
no_payment_due(student663,pos).
no_payment_due(student662,pos).
no_payment_due(student661,pos).
no_payment_due(student660,pos).
no_payment_due(student659,pos).
no_payment_due(student658,pos).
no_payment_due(student656,pos).
no_payment_due(student655,pos).
no_payment_due(student652,pos).
no_payment_due(student651,pos).
no_payment_due(student650,pos).
no_payment_due(student649,pos).
no_payment_due(student647,pos).
no_payment_due(student646,pos).
no_payment_due(student645,pos).
no_payment_due(student642,pos).
no_payment_due(student641,pos).
no_payment_due(student638,pos).
no_payment_due(student635,pos).
no_payment_due(student634,pos).
no_payment_due(student632,pos).
no_payment_due(student631,pos).
no_payment_due(student629,pos).
no_payment_due(student628,pos).
no_payment_due(student627,pos).
no_payment_due(student626,pos).
no_payment_due(student625,pos).
no_payment_due(student624,pos).
no_payment_due(student621,pos).
no_payment_due(student620,pos).
no_payment_due(student619,pos).
no_payment_due(student617,pos).
no_payment_due(student616,pos).
no_payment_due(student615,pos).
no_payment_due(student614,pos).
no_payment_due(student613,pos).
no_payment_due(student612,pos).
no_payment_due(student611,pos).
no_payment_due(student610,pos).
no_payment_due(student609,pos).
no_payment_due(student608,pos).
no_payment_due(student607,pos).
no_payment_due(student606,pos).
no_payment_due(student605,pos).
no_payment_due(student603,pos).
no_payment_due(student602,pos).
no_payment_due(student601,pos).
no_payment_due(student600,pos).
no_payment_due(student599,pos).
no_payment_due(student598,pos).
no_payment_due(student596,pos).
no_payment_due(student595,pos).
no_payment_due(student594,pos).
no_payment_due(student593,pos).
no_payment_due(student592,pos).
no_payment_due(student591,pos).
no_payment_due(student590,pos).
no_payment_due(student589,pos).
no_payment_due(student588,pos).
no_payment_due(student587,pos).
no_payment_due(student585,pos).
no_payment_due(student584,pos).
no_payment_due(student583,pos).
no_payment_due(student581,pos).
no_payment_due(student580,pos).
no_payment_due(student579,pos).
no_payment_due(student578,pos).
no_payment_due(student576,pos).
no_payment_due(student575,pos).
no_payment_due(student573,pos).
no_payment_due(student572,pos).
no_payment_due(student570,pos).
no_payment_due(student569,pos).
no_payment_due(student568,pos).
no_payment_due(student567,pos).
no_payment_due(student565,pos).
no_payment_due(student562,pos).
no_payment_due(student560,pos).
no_payment_due(student559,pos).
no_payment_due(student556,pos).
no_payment_due(student555,pos).
no_payment_due(student554,pos).
no_payment_due(student553,pos).
no_payment_due(student550,pos).
no_payment_due(student547,pos).
no_payment_due(student546,pos).
no_payment_due(student544,pos).
no_payment_due(student541,pos).
no_payment_due(student539,pos).
no_payment_due(student538,pos).
no_payment_due(student536,pos).
no_payment_due(student534,pos).
no_payment_due(student533,pos).
no_payment_due(student531,pos).
no_payment_due(student530,pos).
no_payment_due(student529,pos).
no_payment_due(student527,pos).
no_payment_due(student526,pos).
no_payment_due(student523,pos).
no_payment_due(student522,pos).
no_payment_due(student519,pos).
no_payment_due(student517,pos).
no_payment_due(student515,pos).
no_payment_due(student512,pos).
no_payment_due(student511,pos).
no_payment_due(student508,pos).
no_payment_due(student505,pos).
no_payment_due(student504,pos).
no_payment_due(student503,pos).
no_payment_due(student502,pos).
no_payment_due(student500,pos).
no_payment_due(student498,pos).
no_payment_due(student497,pos).
no_payment_due(student496,pos).
no_payment_due(student495,pos).
no_payment_due(student494,pos).
no_payment_due(student493,pos).
no_payment_due(student492,pos).
no_payment_due(student491,pos).
no_payment_due(student490,pos).
no_payment_due(student488,pos).
no_payment_due(student486,pos).
no_payment_due(student485,pos).
no_payment_due(student481,pos).
no_payment_due(student480,pos).
no_payment_due(student479,pos).
no_payment_due(student477,pos).
no_payment_due(student476,pos).
no_payment_due(student475,pos).
no_payment_due(student474,pos).
no_payment_due(student473,pos).
no_payment_due(student472,pos).
no_payment_due(student470,pos).
no_payment_due(student468,pos).
no_payment_due(student467,pos).
no_payment_due(student465,pos).
no_payment_due(student459,pos).
no_payment_due(student458,pos).
no_payment_due(student452,pos).
no_payment_due(student450,pos).
no_payment_due(student448,pos).
no_payment_due(student447,pos).
no_payment_due(student446,pos).
no_payment_due(student444,pos).
no_payment_due(student443,pos).
no_payment_due(student442,pos).
no_payment_due(student441,pos).
no_payment_due(student440,pos).
no_payment_due(student439,pos).
no_payment_due(student438,pos).
no_payment_due(student436,pos).
no_payment_due(student433,pos).
no_payment_due(student432,pos).
no_payment_due(student431,pos).
no_payment_due(student430,pos).
no_payment_due(student429,pos).
no_payment_due(student428,pos).
no_payment_due(student425,pos).
no_payment_due(student423,pos).
no_payment_due(student422,pos).
no_payment_due(student421,pos).
no_payment_due(student420,pos).
no_payment_due(student417,pos).
no_payment_due(student416,pos).
no_payment_due(student415,pos).
no_payment_due(student414,pos).
no_payment_due(student412,pos).
no_payment_due(student411,pos).
no_payment_due(student410,pos).
no_payment_due(student409,pos).
no_payment_due(student407,pos).
no_payment_due(student406,pos).
no_payment_due(student405,pos).
no_payment_due(student404,pos).
no_payment_due(student403,pos).
no_payment_due(student401,pos).
no_payment_due(student400,pos).
no_payment_due(student399,pos).
no_payment_due(student397,pos).
no_payment_due(student396,pos).
no_payment_due(student395,pos).
no_payment_due(student391,pos).
no_payment_due(student389,pos).
no_payment_due(student388,pos).
no_payment_due(student386,pos).
no_payment_due(student385,pos).
no_payment_due(student384,pos).
no_payment_due(student382,pos).
no_payment_due(student380,pos).
no_payment_due(student378,pos).
no_payment_due(student377,pos).
no_payment_due(student376,pos).
no_payment_due(student373,pos).
no_payment_due(student372,pos).
no_payment_due(student371,pos).
no_payment_due(student370,pos).
no_payment_due(student369,pos).
no_payment_due(student368,pos).
no_payment_due(student367,pos).
no_payment_due(student364,pos).
no_payment_due(student361,pos).
no_payment_due(student359,pos).
no_payment_due(student354,pos).
no_payment_due(student352,pos).
no_payment_due(student351,pos).
no_payment_due(student350,pos).
no_payment_due(student349,pos).
no_payment_due(student347,pos).
no_payment_due(student346,pos).
no_payment_due(student342,pos).
no_payment_due(student340,pos).
no_payment_due(student339,pos).
no_payment_due(student338,pos).
no_payment_due(student337,pos).
no_payment_due(student336,pos).
no_payment_due(student334,pos).
no_payment_due(student333,pos).
no_payment_due(student331,pos).
no_payment_due(student330,pos).
no_payment_due(student329,pos).
no_payment_due(student328,pos).
no_payment_due(student324,pos).
no_payment_due(student323,pos).
no_payment_due(student322,pos).
no_payment_due(student318,pos).
no_payment_due(student317,pos).
no_payment_due(student316,pos).
no_payment_due(student315,pos).
no_payment_due(student314,pos).
no_payment_due(student313,pos).
no_payment_due(student309,pos).
no_payment_due(student308,pos).
no_payment_due(student306,pos).
no_payment_due(student305,pos).
no_payment_due(student304,pos).
no_payment_due(student302,pos).
no_payment_due(student301,pos).
no_payment_due(student300,pos).
no_payment_due(student297,pos).
no_payment_due(student296,pos).
no_payment_due(student295,pos).
no_payment_due(student294,pos).
no_payment_due(student293,pos).
no_payment_due(student291,pos).
no_payment_due(student288,pos).
no_payment_due(student286,pos).
no_payment_due(student285,pos).
no_payment_due(student284,pos).
no_payment_due(student283,pos).
no_payment_due(student282,pos).
no_payment_due(student281,pos).
no_payment_due(student280,pos).
no_payment_due(student279,pos).
no_payment_due(student275,pos).
no_payment_due(student274,pos).
no_payment_due(student273,pos).
no_payment_due(student272,pos).
no_payment_due(student271,pos).
no_payment_due(student270,pos).
no_payment_due(student269,pos).
no_payment_due(student267,pos).
no_payment_due(student263,pos).
no_payment_due(student262,pos).
no_payment_due(student261,pos).
no_payment_due(student260,pos).
no_payment_due(student257,pos).
no_payment_due(student255,pos).
no_payment_due(student253,pos).
no_payment_due(student250,pos).
no_payment_due(student248,pos).
no_payment_due(student247,pos).
no_payment_due(student246,pos).
no_payment_due(student244,pos).
no_payment_due(student242,pos).
no_payment_due(student241,pos).
no_payment_due(student238,pos).
no_payment_due(student237,pos).
no_payment_due(student235,pos).
no_payment_due(student234,pos).
no_payment_due(student233,pos).
no_payment_due(student232,pos).
no_payment_due(student231,pos).
no_payment_due(student229,pos).
no_payment_due(student228,pos).
no_payment_due(student227,pos).
no_payment_due(student226,pos).
no_payment_due(student225,pos).
no_payment_due(student224,pos).
no_payment_due(student222,pos).
no_payment_due(student220,pos).
no_payment_due(student219,pos).
no_payment_due(student217,pos).
no_payment_due(student216,pos).
no_payment_due(student214,pos).
no_payment_due(student213,pos).
no_payment_due(student211,pos).
no_payment_due(student210,pos).
no_payment_due(student209,pos).
no_payment_due(student208,pos).
no_payment_due(student207,pos).
no_payment_due(student204,pos).
no_payment_due(student203,pos).
no_payment_due(student199,pos).
no_payment_due(student198,pos).
no_payment_due(student197,pos).
no_payment_due(student196,pos).
no_payment_due(student195,pos).
no_payment_due(student194,pos).
no_payment_due(student193,pos).
no_payment_due(student191,pos).
no_payment_due(student189,pos).
no_payment_due(student184,pos).
no_payment_due(student183,pos).
no_payment_due(student181,pos).
no_payment_due(student179,pos).
no_payment_due(student178,pos).
no_payment_due(student175,pos).
no_payment_due(student174,pos).
no_payment_due(student173,pos).
no_payment_due(student172,pos).
no_payment_due(student171,pos).
no_payment_due(student170,pos).
no_payment_due(student169,pos).
no_payment_due(student168,pos).
no_payment_due(student167,pos).
no_payment_due(student165,pos).
no_payment_due(student164,pos).
no_payment_due(student163,pos).
no_payment_due(student162,pos).
no_payment_due(student159,pos).
no_payment_due(student158,pos).
no_payment_due(student157,pos).
no_payment_due(student156,pos).
no_payment_due(student155,pos).
no_payment_due(student154,pos).
no_payment_due(student153,pos).
no_payment_due(student152,pos).
no_payment_due(student151,pos).
no_payment_due(student150,pos).
no_payment_due(student148,pos).
no_payment_due(student147,pos).
no_payment_due(student145,pos).
no_payment_due(student143,pos).
no_payment_due(student142,pos).
no_payment_due(student140,pos).
no_payment_due(student139,pos).
no_payment_due(student138,pos).
no_payment_due(student136,pos).
no_payment_due(student135,pos).
no_payment_due(student134,pos).
no_payment_due(student133,pos).
no_payment_due(student130,pos).
no_payment_due(student129,pos).
no_payment_due(student128,pos).
no_payment_due(student127,pos).
no_payment_due(student126,pos).
no_payment_due(student125,pos).
no_payment_due(student122,pos).
no_payment_due(student121,pos).
no_payment_due(student120,pos).
no_payment_due(student119,pos).
no_payment_due(student118,pos).
no_payment_due(student117,pos).
no_payment_due(student114,pos).
no_payment_due(student112,pos).
no_payment_due(student109,pos).
no_payment_due(student108,pos).
no_payment_due(student106,pos).
no_payment_due(student105,pos).
no_payment_due(student104,pos).
no_payment_due(student102,pos).
no_payment_due(student100,pos).
no_payment_due(student99,pos).
no_payment_due(student97,pos).
no_payment_due(student96,pos).
no_payment_due(student95,pos).
no_payment_due(student94,pos).
no_payment_due(student93,pos).
no_payment_due(student92,pos).
no_payment_due(student91,pos).
no_payment_due(student90,pos).
no_payment_due(student84,pos).
no_payment_due(student83,pos).
no_payment_due(student82,pos).
no_payment_due(student81,pos).
no_payment_due(student80,pos).
no_payment_due(student79,pos).
no_payment_due(student77,pos).
no_payment_due(student75,pos).
no_payment_due(student73,pos).
no_payment_due(student72,pos).
no_payment_due(student70,pos).
no_payment_due(student69,pos).
no_payment_due(student68,pos).
no_payment_due(student66,pos).
no_payment_due(student65,pos).
no_payment_due(student64,pos).
no_payment_due(student63,pos).
no_payment_due(student62,pos).
no_payment_due(student59,pos).
no_payment_due(student57,pos).
no_payment_due(student52,pos).
no_payment_due(student51,pos).
no_payment_due(student50,pos).
no_payment_due(student49,pos).
no_payment_due(student48,pos).
no_payment_due(student46,pos).
no_payment_due(student45,pos).
no_payment_due(student43,pos).
no_payment_due(student42,pos).
no_payment_due(student41,pos).
no_payment_due(student40,pos).
no_payment_due(student39,pos).
no_payment_due(student37,pos).
no_payment_due(student33,pos).
no_payment_due(student32,pos).
no_payment_due(student31,pos).
no_payment_due(student30,pos).
no_payment_due(student28,pos).
no_payment_due(student26,pos).
no_payment_due(student24,pos).
no_payment_due(student23,pos).
no_payment_due(student22,pos).
no_payment_due(student21,pos).
no_payment_due(student19,pos).
no_payment_due(student17,pos).
no_payment_due(student15,pos).
no_payment_due(student13,pos).
no_payment_due(student12,pos).
no_payment_due(student11,pos).
no_payment_due(student9,pos).
no_payment_due(student8,pos).
no_payment_due(student7,pos).
no_payment_due(student6,pos).
no_payment_due(student4,pos).
no_payment_due(student2,pos).
no_payment_due(student1,pos).
no_payment_due(student997,neg).
no_payment_due(student995,neg).
no_payment_due(student991,neg).
no_payment_due(student988,neg).
no_payment_due(student986,neg).
no_payment_due(student982,neg).
no_payment_due(student980,neg).
no_payment_due(student979,neg).
no_payment_due(student978,neg).
no_payment_due(student974,neg).
no_payment_due(student973,neg).
no_payment_due(student971,neg).
no_payment_due(student966,neg).
no_payment_due(student965,neg).
no_payment_due(student964,neg).
no_payment_due(student961,neg).
no_payment_due(student960,neg).
no_payment_due(student957,neg).
no_payment_due(student954,neg).
no_payment_due(student951,neg).
no_payment_due(student944,neg).
no_payment_due(student941,neg).
no_payment_due(student939,neg).
no_payment_due(student938,neg).
no_payment_due(student934,neg).
no_payment_due(student933,neg).
no_payment_due(student931,neg).
no_payment_due(student930,neg).
no_payment_due(student929,neg).
no_payment_due(student925,neg).
no_payment_due(student922,neg).
no_payment_due(student921,neg).
no_payment_due(student919,neg).
no_payment_due(student917,neg).
no_payment_due(student914,neg).
no_payment_due(student912,neg).
no_payment_due(student911,neg).
no_payment_due(student907,neg).
no_payment_due(student903,neg).
no_payment_due(student900,neg).
no_payment_due(student899,neg).
no_payment_due(student898,neg).
no_payment_due(student892,neg).
no_payment_due(student889,neg).
no_payment_due(student886,neg).
no_payment_due(student884,neg).
no_payment_due(student883,neg).
no_payment_due(student882,neg).
no_payment_due(student880,neg).
no_payment_due(student878,neg).
no_payment_due(student876,neg).
no_payment_due(student875,neg).
no_payment_due(student873,neg).
no_payment_due(student872,neg).
no_payment_due(student869,neg).
no_payment_due(student865,neg).
no_payment_due(student862,neg).
no_payment_due(student861,neg).
no_payment_due(student860,neg).
no_payment_due(student857,neg).
no_payment_due(student853,neg).
no_payment_due(student851,neg).
no_payment_due(student848,neg).
no_payment_due(student845,neg).
no_payment_due(student844,neg).
no_payment_due(student843,neg).
no_payment_due(student839,neg).
no_payment_due(student837,neg).
no_payment_due(student834,neg).
no_payment_due(student833,neg).
no_payment_due(student829,neg).
no_payment_due(student826,neg).
no_payment_due(student824,neg).
no_payment_due(student822,neg).
no_payment_due(student819,neg).
no_payment_due(student818,neg).
no_payment_due(student816,neg).
no_payment_due(student815,neg).
no_payment_due(student813,neg).
no_payment_due(student811,neg).
no_payment_due(student810,neg).
no_payment_due(student802,neg).
no_payment_due(student801,neg).
no_payment_due(student799,neg).
no_payment_due(student796,neg).
no_payment_due(student793,neg).
no_payment_due(student791,neg).
no_payment_due(student786,neg).
no_payment_due(student784,neg).
no_payment_due(student782,neg).
no_payment_due(student777,neg).
no_payment_due(student772,neg).
no_payment_due(student771,neg).
no_payment_due(student767,neg).
no_payment_due(student766,neg).
no_payment_due(student763,neg).
no_payment_due(student759,neg).
no_payment_due(student756,neg).
no_payment_due(student755,neg).
no_payment_due(student752,neg).
no_payment_due(student737,neg).
no_payment_due(student736,neg).
no_payment_due(student731,neg).
no_payment_due(student730,neg).
no_payment_due(student728,neg).
no_payment_due(student726,neg).
no_payment_due(student725,neg).
no_payment_due(student722,neg).
no_payment_due(student720,neg).
no_payment_due(student718,neg).
no_payment_due(student716,neg).
no_payment_due(student715,neg).
no_payment_due(student713,neg).
no_payment_due(student711,neg).
no_payment_due(student708,neg).
no_payment_due(student707,neg).
no_payment_due(student706,neg).
no_payment_due(student704,neg).
no_payment_due(student703,neg).
no_payment_due(student695,neg).
no_payment_due(student694,neg).
no_payment_due(student693,neg).
no_payment_due(student692,neg).
no_payment_due(student691,neg).
no_payment_due(student687,neg).
no_payment_due(student685,neg).
no_payment_due(student683,neg).
no_payment_due(student681,neg).
no_payment_due(student675,neg).
no_payment_due(student671,neg).
no_payment_due(student669,neg).
no_payment_due(student657,neg).
no_payment_due(student654,neg).
no_payment_due(student653,neg).
no_payment_due(student648,neg).
no_payment_due(student644,neg).
no_payment_due(student643,neg).
no_payment_due(student640,neg).
no_payment_due(student639,neg).
no_payment_due(student637,neg).
no_payment_due(student636,neg).
no_payment_due(student633,neg).
no_payment_due(student630,neg).
no_payment_due(student623,neg).
no_payment_due(student622,neg).
no_payment_due(student618,neg).
no_payment_due(student604,neg).
no_payment_due(student597,neg).
no_payment_due(student586,neg).
no_payment_due(student582,neg).
no_payment_due(student577,neg).
no_payment_due(student574,neg).
no_payment_due(student571,neg).
no_payment_due(student566,neg).
no_payment_due(student564,neg).
no_payment_due(student563,neg).
no_payment_due(student561,neg).
no_payment_due(student558,neg).
no_payment_due(student557,neg).
no_payment_due(student552,neg).
no_payment_due(student551,neg).
no_payment_due(student549,neg).
no_payment_due(student548,neg).
no_payment_due(student545,neg).
no_payment_due(student543,neg).
no_payment_due(student542,neg).
no_payment_due(student540,neg).
no_payment_due(student537,neg).
no_payment_due(student535,neg).
no_payment_due(student532,neg).
no_payment_due(student528,neg).
no_payment_due(student525,neg).
no_payment_due(student524,neg).
no_payment_due(student521,neg).
no_payment_due(student520,neg).
no_payment_due(student518,neg).
no_payment_due(student516,neg).
no_payment_due(student514,neg).
no_payment_due(student513,neg).
no_payment_due(student510,neg).
no_payment_due(student509,neg).
no_payment_due(student507,neg).
no_payment_due(student506,neg).
no_payment_due(student501,neg).
no_payment_due(student499,neg).
no_payment_due(student489,neg).
no_payment_due(student487,neg).
no_payment_due(student484,neg).
no_payment_due(student483,neg).
no_payment_due(student482,neg).
no_payment_due(student478,neg).
no_payment_due(student471,neg).
no_payment_due(student469,neg).
no_payment_due(student466,neg).
no_payment_due(student464,neg).
no_payment_due(student463,neg).
no_payment_due(student462,neg).
no_payment_due(student461,neg).
no_payment_due(student460,neg).
no_payment_due(student457,neg).
no_payment_due(student456,neg).
no_payment_due(student455,neg).
no_payment_due(student454,neg).
no_payment_due(student453,neg).
no_payment_due(student451,neg).
no_payment_due(student449,neg).
no_payment_due(student445,neg).
no_payment_due(student437,neg).
no_payment_due(student435,neg).
no_payment_due(student434,neg).
no_payment_due(student427,neg).
no_payment_due(student426,neg).
no_payment_due(student424,neg).
no_payment_due(student419,neg).
no_payment_due(student418,neg).
no_payment_due(student413,neg).
no_payment_due(student408,neg).
no_payment_due(student402,neg).
no_payment_due(student398,neg).
no_payment_due(student394,neg).
no_payment_due(student393,neg).
no_payment_due(student392,neg).
no_payment_due(student390,neg).
no_payment_due(student387,neg).
no_payment_due(student383,neg).
no_payment_due(student381,neg).
no_payment_due(student379,neg).
no_payment_due(student375,neg).
no_payment_due(student374,neg).
no_payment_due(student366,neg).
no_payment_due(student365,neg).
no_payment_due(student363,neg).
no_payment_due(student362,neg).
no_payment_due(student360,neg).
no_payment_due(student358,neg).
no_payment_due(student357,neg).
no_payment_due(student356,neg).
no_payment_due(student355,neg).
no_payment_due(student353,neg).
no_payment_due(student348,neg).
no_payment_due(student345,neg).
no_payment_due(student344,neg).
no_payment_due(student343,neg).
no_payment_due(student341,neg).
no_payment_due(student335,neg).
no_payment_due(student332,neg).
no_payment_due(student327,neg).
no_payment_due(student326,neg).
no_payment_due(student325,neg).
no_payment_due(student321,neg).
no_payment_due(student320,neg).
no_payment_due(student319,neg).
no_payment_due(student312,neg).
no_payment_due(student311,neg).
no_payment_due(student310,neg).
no_payment_due(student307,neg).
no_payment_due(student303,neg).
no_payment_due(student299,neg).
no_payment_due(student298,neg).
no_payment_due(student292,neg).
no_payment_due(student290,neg).
no_payment_due(student289,neg).
no_payment_due(student287,neg).
no_payment_due(student278,neg).
no_payment_due(student277,neg).
no_payment_due(student276,neg).
no_payment_due(student268,neg).
no_payment_due(student266,neg).
no_payment_due(student265,neg).
no_payment_due(student264,neg).
no_payment_due(student259,neg).
no_payment_due(student258,neg).
no_payment_due(student256,neg).
no_payment_due(student254,neg).
no_payment_due(student252,neg).
no_payment_due(student251,neg).
no_payment_due(student249,neg).
no_payment_due(student245,neg).
no_payment_due(student243,neg).
no_payment_due(student240,neg).
no_payment_due(student239,neg).
no_payment_due(student236,neg).
no_payment_due(student230,neg).
no_payment_due(student223,neg).
no_payment_due(student221,neg).
no_payment_due(student218,neg).
no_payment_due(student215,neg).
no_payment_due(student212,neg).
no_payment_due(student206,neg).
no_payment_due(student205,neg).
no_payment_due(student202,neg).
no_payment_due(student201,neg).
no_payment_due(student200,neg).
no_payment_due(student192,neg).
no_payment_due(student190,neg).
no_payment_due(student188,neg).
no_payment_due(student187,neg).
no_payment_due(student186,neg).
no_payment_due(student185,neg).
no_payment_due(student182,neg).
no_payment_due(student180,neg).
no_payment_due(student177,neg).
no_payment_due(student176,neg).
no_payment_due(student166,neg).
no_payment_due(student161,neg).
no_payment_due(student160,neg).
no_payment_due(student149,neg).
no_payment_due(student146,neg).
no_payment_due(student144,neg).
no_payment_due(student141,neg).
no_payment_due(student137,neg).
no_payment_due(student132,neg).
no_payment_due(student131,neg).
no_payment_due(student124,neg).
no_payment_due(student123,neg).
no_payment_due(student116,neg).
no_payment_due(student115,neg).
no_payment_due(student113,neg).
no_payment_due(student111,neg).
no_payment_due(student110,neg).
no_payment_due(student107,neg).
no_payment_due(student103,neg).
no_payment_due(student101,neg).
no_payment_due(student98,neg).
no_payment_due(student89,neg).
no_payment_due(student88,neg).
no_payment_due(student87,neg).
no_payment_due(student86,neg).
no_payment_due(student85,neg).
no_payment_due(student78,neg).
no_payment_due(student76,neg).
no_payment_due(student74,neg).
no_payment_due(student71,neg).
no_payment_due(student67,neg).
no_payment_due(student61,neg).
no_payment_due(student60,neg).
no_payment_due(student58,neg).
no_payment_due(student56,neg).
no_payment_due(student55,neg).
no_payment_due(student54,neg).
no_payment_due(student53,neg).
no_payment_due(student47,neg).
no_payment_due(student44,neg).
no_payment_due(student38,neg).
no_payment_due(student36,neg).
no_payment_due(student35,neg).
no_payment_due(student34,neg).
no_payment_due(student29,neg).
no_payment_due(student27,neg).
no_payment_due(student25,neg).
no_payment_due(student20,neg).
no_payment_due(student18,neg).
no_payment_due(student16,neg).
no_payment_due(student14,neg).
no_payment_due(student10,neg).
no_payment_due(student5,neg).
no_payment_due(student3,neg).
